# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.warnings_settings_request import WarningsSettingsRequest

PatchedAdminOrganizationUpdateRequestWarningsSettings = typing.Union[
    WarningsSettingsRequest, typing.Optional[typing.Any]
]
