# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_condition_request_condition_policy_connector import CreateConditionRequestConditionPolicyConnector
from .create_condition_request_condition_policy_rules_item import CreateConditionRequestConditionPolicyRulesItem


class CreateConditionRequestConditionPolicy(UniversalBaseModel):
    """
    Policy defining evaluation rules.
    """

    rules: typing.List[CreateConditionRequestConditionPolicyRulesItem] = pydantic.Field()
    """
    Array of rule objects.
    """

    connector: CreateConditionRequestConditionPolicyConnector = pydantic.Field()
    """
    How to combine rules.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
