# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_condition_response_condition_policy_rules_item import CreateConditionResponseConditionPolicyRulesItem


class CreateConditionResponseConditionPolicy(UniversalBaseModel):
    rules: typing.Optional[typing.List[CreateConditionResponseConditionPolicyRulesItem]] = None
    connector: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
