# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .api_workflows_commits_create_response import ApiWorkflowsCommitsCreateResponse
    from .api_workflows_commits_create_response_graph import ApiWorkflowsCommitsCreateResponseGraph
    from .api_workflows_commits_create_response_tags_item import ApiWorkflowsCommitsCreateResponseTagsItem
    from .api_workflows_commits_create_response_tasks_item import ApiWorkflowsCommitsCreateResponseTasksItem
    from .api_workflows_commits_create_response_tasks_item_next import ApiWorkflowsCommitsCreateResponseTasksItemNext
    from .api_workflows_commits_create_response_trigger_event_type import (
        ApiWorkflowsCommitsCreateResponseTriggerEventType,
    )
    from .api_workflows_commits_create_response_type import ApiWorkflowsCommitsCreateResponseType
    from .api_workflows_list_request_trigger_event_type import ApiWorkflowsListRequestTriggerEventType
    from .api_workflows_list_request_type import ApiWorkflowsListRequestType
    from .api_workflows_list_response import ApiWorkflowsListResponse
    from .api_workflows_list_response_results_item import ApiWorkflowsListResponseResultsItem
    from .api_workflows_list_response_results_item_editor import ApiWorkflowsListResponseResultsItemEditor
    from .api_workflows_list_response_results_item_editor_id import ApiWorkflowsListResponseResultsItemEditorId
    from .api_workflows_list_response_results_item_tags_item import ApiWorkflowsListResponseResultsItemTagsItem
    from .api_workflows_list_response_results_item_trigger_event_type import (
        ApiWorkflowsListResponseResultsItemTriggerEventType,
    )
    from .api_workflows_list_response_results_item_type import ApiWorkflowsListResponseResultsItemType
    from .create_workflow_request_tasks_item import CreateWorkflowRequestTasksItem
    from .create_workflow_request_tasks_item_next import CreateWorkflowRequestTasksItemNext
    from .create_workflow_request_trigger_event_type import CreateWorkflowRequestTriggerEventType
    from .create_workflow_request_type import CreateWorkflowRequestType
    from .create_workflow_response import CreateWorkflowResponse
    from .create_workflow_response_graph import CreateWorkflowResponseGraph
    from .create_workflow_response_tags_item import CreateWorkflowResponseTagsItem
    from .create_workflow_response_tasks_item import CreateWorkflowResponseTasksItem
    from .create_workflow_response_tasks_item_next import CreateWorkflowResponseTasksItemNext
    from .create_workflow_response_trigger_event_type import CreateWorkflowResponseTriggerEventType
    from .create_workflow_response_type import CreateWorkflowResponseType
    from .create_workflow_version_request_tasks_item import CreateWorkflowVersionRequestTasksItem
    from .create_workflow_version_request_tasks_item_next import CreateWorkflowVersionRequestTasksItemNext
    from .create_workflow_version_request_trigger_event_type import CreateWorkflowVersionRequestTriggerEventType
    from .create_workflow_version_request_type import CreateWorkflowVersionRequestType
    from .create_workflow_version_response import CreateWorkflowVersionResponse
    from .create_workflow_version_response_graph import CreateWorkflowVersionResponseGraph
    from .create_workflow_version_response_tags_item import CreateWorkflowVersionResponseTagsItem
    from .create_workflow_version_response_tasks_item import CreateWorkflowVersionResponseTasksItem
    from .create_workflow_version_response_tasks_item_next import CreateWorkflowVersionResponseTasksItemNext
    from .create_workflow_version_response_trigger_event_type import CreateWorkflowVersionResponseTriggerEventType
    from .create_workflow_version_response_type import CreateWorkflowVersionResponseType
    from .deploy_workflow_response import DeployWorkflowResponse
    from .filter_workflows_request_trigger_event_type import FilterWorkflowsRequestTriggerEventType
    from .filter_workflows_request_type import FilterWorkflowsRequestType
    from .filter_workflows_response import FilterWorkflowsResponse
    from .filter_workflows_response_results_item import FilterWorkflowsResponseResultsItem
    from .filter_workflows_response_results_item_editor import FilterWorkflowsResponseResultsItemEditor
    from .filter_workflows_response_results_item_editor_id import FilterWorkflowsResponseResultsItemEditorId
    from .filter_workflows_response_results_item_tags_item import FilterWorkflowsResponseResultsItemTagsItem
    from .filter_workflows_response_results_item_trigger_event_type import (
        FilterWorkflowsResponseResultsItemTriggerEventType,
    )
    from .filter_workflows_response_results_item_type import FilterWorkflowsResponseResultsItemType
    from .get_workflow_response import GetWorkflowResponse
    from .get_workflow_response_created_at import GetWorkflowResponseCreatedAt
    from .get_workflow_response_created_at_graph import GetWorkflowResponseCreatedAtGraph
    from .get_workflow_response_created_at_tags_item import GetWorkflowResponseCreatedAtTagsItem
    from .get_workflow_response_created_at_tasks_item import GetWorkflowResponseCreatedAtTasksItem
    from .get_workflow_response_created_at_tasks_item_next import GetWorkflowResponseCreatedAtTasksItemNext
    from .get_workflow_response_created_at_trigger_event_type import GetWorkflowResponseCreatedAtTriggerEventType
    from .get_workflow_response_created_at_type import GetWorkflowResponseCreatedAtType
    from .get_workflow_response_schema_version import GetWorkflowResponseSchemaVersion
    from .get_workflow_response_schema_version_schema_version import GetWorkflowResponseSchemaVersionSchemaVersion
    from .get_workflow_response_schema_version_workflow import GetWorkflowResponseSchemaVersionWorkflow
    from .get_workflow_response_schema_version_workflow_tasks_item import (
        GetWorkflowResponseSchemaVersionWorkflowTasksItem,
    )
    from .get_workflow_response_schema_version_workflow_tasks_item_next import (
        GetWorkflowResponseSchemaVersionWorkflowTasksItemNext,
    )
    from .get_workflow_response_schema_version_workflow_trigger_event_type import (
        GetWorkflowResponseSchemaVersionWorkflowTriggerEventType,
    )
    from .get_workflow_version_response import GetWorkflowVersionResponse
    from .get_workflow_version_response_graph import GetWorkflowVersionResponseGraph
    from .get_workflow_version_response_tags_item import GetWorkflowVersionResponseTagsItem
    from .get_workflow_version_response_tasks_item import GetWorkflowVersionResponseTasksItem
    from .get_workflow_version_response_tasks_item_next import GetWorkflowVersionResponseTasksItemNext
    from .get_workflow_version_response_trigger_event_type import GetWorkflowVersionResponseTriggerEventType
    from .get_workflow_version_response_type import GetWorkflowVersionResponseType
    from .list_workflow_versions_response import ListWorkflowVersionsResponse
    from .list_workflow_versions_response_results_item import ListWorkflowVersionsResponseResultsItem
    from .list_workflow_versions_response_results_item_editor import ListWorkflowVersionsResponseResultsItemEditor
    from .list_workflow_versions_response_results_item_editor_id import ListWorkflowVersionsResponseResultsItemEditorId
    from .list_workflow_versions_response_results_item_tags_item import ListWorkflowVersionsResponseResultsItemTagsItem
    from .list_workflow_versions_response_results_item_trigger_event_type import (
        ListWorkflowVersionsResponseResultsItemTriggerEventType,
    )
    from .list_workflow_versions_response_results_item_type import ListWorkflowVersionsResponseResultsItemType
    from .update_workflow_request_tasks_item import UpdateWorkflowRequestTasksItem
    from .update_workflow_request_tasks_item_next import UpdateWorkflowRequestTasksItemNext
    from .update_workflow_request_trigger_event_type import UpdateWorkflowRequestTriggerEventType
    from .update_workflow_request_type import UpdateWorkflowRequestType
    from .update_workflow_response import UpdateWorkflowResponse
    from .update_workflow_response_graph import UpdateWorkflowResponseGraph
    from .update_workflow_response_tags_item import UpdateWorkflowResponseTagsItem
    from .update_workflow_response_tasks_item import UpdateWorkflowResponseTasksItem
    from .update_workflow_response_tasks_item_next import UpdateWorkflowResponseTasksItemNext
    from .update_workflow_response_trigger_event_type import UpdateWorkflowResponseTriggerEventType
    from .update_workflow_response_type import UpdateWorkflowResponseType
    from .update_workflow_version_request_tasks_item import UpdateWorkflowVersionRequestTasksItem
    from .update_workflow_version_request_tasks_item_next import UpdateWorkflowVersionRequestTasksItemNext
    from .update_workflow_version_request_trigger_event_type import UpdateWorkflowVersionRequestTriggerEventType
    from .update_workflow_version_request_type import UpdateWorkflowVersionRequestType
    from .update_workflow_version_response import UpdateWorkflowVersionResponse
    from .update_workflow_version_response_graph import UpdateWorkflowVersionResponseGraph
    from .update_workflow_version_response_tags_item import UpdateWorkflowVersionResponseTagsItem
    from .update_workflow_version_response_tasks_item import UpdateWorkflowVersionResponseTasksItem
    from .update_workflow_version_response_tasks_item_next import UpdateWorkflowVersionResponseTasksItemNext
    from .update_workflow_version_response_trigger_event_type import UpdateWorkflowVersionResponseTriggerEventType
    from .update_workflow_version_response_type import UpdateWorkflowVersionResponseType
    from .validate_workflow_response import ValidateWorkflowResponse
    from .validate_workflow_response_status import ValidateWorkflowResponseStatus
    from .validate_workflow_response_task_results_item import ValidateWorkflowResponseTaskResultsItem
    from .validate_workflow_response_task_results_item_status import ValidateWorkflowResponseTaskResultsItemStatus
    from .validate_workflow_response_validation import ValidateWorkflowResponseValidation
_dynamic_imports: typing.Dict[str, str] = {
    "ApiWorkflowsCommitsCreateResponse": ".api_workflows_commits_create_response",
    "ApiWorkflowsCommitsCreateResponseGraph": ".api_workflows_commits_create_response_graph",
    "ApiWorkflowsCommitsCreateResponseTagsItem": ".api_workflows_commits_create_response_tags_item",
    "ApiWorkflowsCommitsCreateResponseTasksItem": ".api_workflows_commits_create_response_tasks_item",
    "ApiWorkflowsCommitsCreateResponseTasksItemNext": ".api_workflows_commits_create_response_tasks_item_next",
    "ApiWorkflowsCommitsCreateResponseTriggerEventType": ".api_workflows_commits_create_response_trigger_event_type",
    "ApiWorkflowsCommitsCreateResponseType": ".api_workflows_commits_create_response_type",
    "ApiWorkflowsListRequestTriggerEventType": ".api_workflows_list_request_trigger_event_type",
    "ApiWorkflowsListRequestType": ".api_workflows_list_request_type",
    "ApiWorkflowsListResponse": ".api_workflows_list_response",
    "ApiWorkflowsListResponseResultsItem": ".api_workflows_list_response_results_item",
    "ApiWorkflowsListResponseResultsItemEditor": ".api_workflows_list_response_results_item_editor",
    "ApiWorkflowsListResponseResultsItemEditorId": ".api_workflows_list_response_results_item_editor_id",
    "ApiWorkflowsListResponseResultsItemTagsItem": ".api_workflows_list_response_results_item_tags_item",
    "ApiWorkflowsListResponseResultsItemTriggerEventType": ".api_workflows_list_response_results_item_trigger_event_type",
    "ApiWorkflowsListResponseResultsItemType": ".api_workflows_list_response_results_item_type",
    "CreateWorkflowRequestTasksItem": ".create_workflow_request_tasks_item",
    "CreateWorkflowRequestTasksItemNext": ".create_workflow_request_tasks_item_next",
    "CreateWorkflowRequestTriggerEventType": ".create_workflow_request_trigger_event_type",
    "CreateWorkflowRequestType": ".create_workflow_request_type",
    "CreateWorkflowResponse": ".create_workflow_response",
    "CreateWorkflowResponseGraph": ".create_workflow_response_graph",
    "CreateWorkflowResponseTagsItem": ".create_workflow_response_tags_item",
    "CreateWorkflowResponseTasksItem": ".create_workflow_response_tasks_item",
    "CreateWorkflowResponseTasksItemNext": ".create_workflow_response_tasks_item_next",
    "CreateWorkflowResponseTriggerEventType": ".create_workflow_response_trigger_event_type",
    "CreateWorkflowResponseType": ".create_workflow_response_type",
    "CreateWorkflowVersionRequestTasksItem": ".create_workflow_version_request_tasks_item",
    "CreateWorkflowVersionRequestTasksItemNext": ".create_workflow_version_request_tasks_item_next",
    "CreateWorkflowVersionRequestTriggerEventType": ".create_workflow_version_request_trigger_event_type",
    "CreateWorkflowVersionRequestType": ".create_workflow_version_request_type",
    "CreateWorkflowVersionResponse": ".create_workflow_version_response",
    "CreateWorkflowVersionResponseGraph": ".create_workflow_version_response_graph",
    "CreateWorkflowVersionResponseTagsItem": ".create_workflow_version_response_tags_item",
    "CreateWorkflowVersionResponseTasksItem": ".create_workflow_version_response_tasks_item",
    "CreateWorkflowVersionResponseTasksItemNext": ".create_workflow_version_response_tasks_item_next",
    "CreateWorkflowVersionResponseTriggerEventType": ".create_workflow_version_response_trigger_event_type",
    "CreateWorkflowVersionResponseType": ".create_workflow_version_response_type",
    "DeployWorkflowResponse": ".deploy_workflow_response",
    "FilterWorkflowsRequestTriggerEventType": ".filter_workflows_request_trigger_event_type",
    "FilterWorkflowsRequestType": ".filter_workflows_request_type",
    "FilterWorkflowsResponse": ".filter_workflows_response",
    "FilterWorkflowsResponseResultsItem": ".filter_workflows_response_results_item",
    "FilterWorkflowsResponseResultsItemEditor": ".filter_workflows_response_results_item_editor",
    "FilterWorkflowsResponseResultsItemEditorId": ".filter_workflows_response_results_item_editor_id",
    "FilterWorkflowsResponseResultsItemTagsItem": ".filter_workflows_response_results_item_tags_item",
    "FilterWorkflowsResponseResultsItemTriggerEventType": ".filter_workflows_response_results_item_trigger_event_type",
    "FilterWorkflowsResponseResultsItemType": ".filter_workflows_response_results_item_type",
    "GetWorkflowResponse": ".get_workflow_response",
    "GetWorkflowResponseCreatedAt": ".get_workflow_response_created_at",
    "GetWorkflowResponseCreatedAtGraph": ".get_workflow_response_created_at_graph",
    "GetWorkflowResponseCreatedAtTagsItem": ".get_workflow_response_created_at_tags_item",
    "GetWorkflowResponseCreatedAtTasksItem": ".get_workflow_response_created_at_tasks_item",
    "GetWorkflowResponseCreatedAtTasksItemNext": ".get_workflow_response_created_at_tasks_item_next",
    "GetWorkflowResponseCreatedAtTriggerEventType": ".get_workflow_response_created_at_trigger_event_type",
    "GetWorkflowResponseCreatedAtType": ".get_workflow_response_created_at_type",
    "GetWorkflowResponseSchemaVersion": ".get_workflow_response_schema_version",
    "GetWorkflowResponseSchemaVersionSchemaVersion": ".get_workflow_response_schema_version_schema_version",
    "GetWorkflowResponseSchemaVersionWorkflow": ".get_workflow_response_schema_version_workflow",
    "GetWorkflowResponseSchemaVersionWorkflowTasksItem": ".get_workflow_response_schema_version_workflow_tasks_item",
    "GetWorkflowResponseSchemaVersionWorkflowTasksItemNext": ".get_workflow_response_schema_version_workflow_tasks_item_next",
    "GetWorkflowResponseSchemaVersionWorkflowTriggerEventType": ".get_workflow_response_schema_version_workflow_trigger_event_type",
    "GetWorkflowVersionResponse": ".get_workflow_version_response",
    "GetWorkflowVersionResponseGraph": ".get_workflow_version_response_graph",
    "GetWorkflowVersionResponseTagsItem": ".get_workflow_version_response_tags_item",
    "GetWorkflowVersionResponseTasksItem": ".get_workflow_version_response_tasks_item",
    "GetWorkflowVersionResponseTasksItemNext": ".get_workflow_version_response_tasks_item_next",
    "GetWorkflowVersionResponseTriggerEventType": ".get_workflow_version_response_trigger_event_type",
    "GetWorkflowVersionResponseType": ".get_workflow_version_response_type",
    "ListWorkflowVersionsResponse": ".list_workflow_versions_response",
    "ListWorkflowVersionsResponseResultsItem": ".list_workflow_versions_response_results_item",
    "ListWorkflowVersionsResponseResultsItemEditor": ".list_workflow_versions_response_results_item_editor",
    "ListWorkflowVersionsResponseResultsItemEditorId": ".list_workflow_versions_response_results_item_editor_id",
    "ListWorkflowVersionsResponseResultsItemTagsItem": ".list_workflow_versions_response_results_item_tags_item",
    "ListWorkflowVersionsResponseResultsItemTriggerEventType": ".list_workflow_versions_response_results_item_trigger_event_type",
    "ListWorkflowVersionsResponseResultsItemType": ".list_workflow_versions_response_results_item_type",
    "UpdateWorkflowRequestTasksItem": ".update_workflow_request_tasks_item",
    "UpdateWorkflowRequestTasksItemNext": ".update_workflow_request_tasks_item_next",
    "UpdateWorkflowRequestTriggerEventType": ".update_workflow_request_trigger_event_type",
    "UpdateWorkflowRequestType": ".update_workflow_request_type",
    "UpdateWorkflowResponse": ".update_workflow_response",
    "UpdateWorkflowResponseGraph": ".update_workflow_response_graph",
    "UpdateWorkflowResponseTagsItem": ".update_workflow_response_tags_item",
    "UpdateWorkflowResponseTasksItem": ".update_workflow_response_tasks_item",
    "UpdateWorkflowResponseTasksItemNext": ".update_workflow_response_tasks_item_next",
    "UpdateWorkflowResponseTriggerEventType": ".update_workflow_response_trigger_event_type",
    "UpdateWorkflowResponseType": ".update_workflow_response_type",
    "UpdateWorkflowVersionRequestTasksItem": ".update_workflow_version_request_tasks_item",
    "UpdateWorkflowVersionRequestTasksItemNext": ".update_workflow_version_request_tasks_item_next",
    "UpdateWorkflowVersionRequestTriggerEventType": ".update_workflow_version_request_trigger_event_type",
    "UpdateWorkflowVersionRequestType": ".update_workflow_version_request_type",
    "UpdateWorkflowVersionResponse": ".update_workflow_version_response",
    "UpdateWorkflowVersionResponseGraph": ".update_workflow_version_response_graph",
    "UpdateWorkflowVersionResponseTagsItem": ".update_workflow_version_response_tags_item",
    "UpdateWorkflowVersionResponseTasksItem": ".update_workflow_version_response_tasks_item",
    "UpdateWorkflowVersionResponseTasksItemNext": ".update_workflow_version_response_tasks_item_next",
    "UpdateWorkflowVersionResponseTriggerEventType": ".update_workflow_version_response_trigger_event_type",
    "UpdateWorkflowVersionResponseType": ".update_workflow_version_response_type",
    "ValidateWorkflowResponse": ".validate_workflow_response",
    "ValidateWorkflowResponseStatus": ".validate_workflow_response_status",
    "ValidateWorkflowResponseTaskResultsItem": ".validate_workflow_response_task_results_item",
    "ValidateWorkflowResponseTaskResultsItemStatus": ".validate_workflow_response_task_results_item_status",
    "ValidateWorkflowResponseValidation": ".validate_workflow_response_validation",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ApiWorkflowsCommitsCreateResponse",
    "ApiWorkflowsCommitsCreateResponseGraph",
    "ApiWorkflowsCommitsCreateResponseTagsItem",
    "ApiWorkflowsCommitsCreateResponseTasksItem",
    "ApiWorkflowsCommitsCreateResponseTasksItemNext",
    "ApiWorkflowsCommitsCreateResponseTriggerEventType",
    "ApiWorkflowsCommitsCreateResponseType",
    "ApiWorkflowsListRequestTriggerEventType",
    "ApiWorkflowsListRequestType",
    "ApiWorkflowsListResponse",
    "ApiWorkflowsListResponseResultsItem",
    "ApiWorkflowsListResponseResultsItemEditor",
    "ApiWorkflowsListResponseResultsItemEditorId",
    "ApiWorkflowsListResponseResultsItemTagsItem",
    "ApiWorkflowsListResponseResultsItemTriggerEventType",
    "ApiWorkflowsListResponseResultsItemType",
    "CreateWorkflowRequestTasksItem",
    "CreateWorkflowRequestTasksItemNext",
    "CreateWorkflowRequestTriggerEventType",
    "CreateWorkflowRequestType",
    "CreateWorkflowResponse",
    "CreateWorkflowResponseGraph",
    "CreateWorkflowResponseTagsItem",
    "CreateWorkflowResponseTasksItem",
    "CreateWorkflowResponseTasksItemNext",
    "CreateWorkflowResponseTriggerEventType",
    "CreateWorkflowResponseType",
    "CreateWorkflowVersionRequestTasksItem",
    "CreateWorkflowVersionRequestTasksItemNext",
    "CreateWorkflowVersionRequestTriggerEventType",
    "CreateWorkflowVersionRequestType",
    "CreateWorkflowVersionResponse",
    "CreateWorkflowVersionResponseGraph",
    "CreateWorkflowVersionResponseTagsItem",
    "CreateWorkflowVersionResponseTasksItem",
    "CreateWorkflowVersionResponseTasksItemNext",
    "CreateWorkflowVersionResponseTriggerEventType",
    "CreateWorkflowVersionResponseType",
    "DeployWorkflowResponse",
    "FilterWorkflowsRequestTriggerEventType",
    "FilterWorkflowsRequestType",
    "FilterWorkflowsResponse",
    "FilterWorkflowsResponseResultsItem",
    "FilterWorkflowsResponseResultsItemEditor",
    "FilterWorkflowsResponseResultsItemEditorId",
    "FilterWorkflowsResponseResultsItemTagsItem",
    "FilterWorkflowsResponseResultsItemTriggerEventType",
    "FilterWorkflowsResponseResultsItemType",
    "GetWorkflowResponse",
    "GetWorkflowResponseCreatedAt",
    "GetWorkflowResponseCreatedAtGraph",
    "GetWorkflowResponseCreatedAtTagsItem",
    "GetWorkflowResponseCreatedAtTasksItem",
    "GetWorkflowResponseCreatedAtTasksItemNext",
    "GetWorkflowResponseCreatedAtTriggerEventType",
    "GetWorkflowResponseCreatedAtType",
    "GetWorkflowResponseSchemaVersion",
    "GetWorkflowResponseSchemaVersionSchemaVersion",
    "GetWorkflowResponseSchemaVersionWorkflow",
    "GetWorkflowResponseSchemaVersionWorkflowTasksItem",
    "GetWorkflowResponseSchemaVersionWorkflowTasksItemNext",
    "GetWorkflowResponseSchemaVersionWorkflowTriggerEventType",
    "GetWorkflowVersionResponse",
    "GetWorkflowVersionResponseGraph",
    "GetWorkflowVersionResponseTagsItem",
    "GetWorkflowVersionResponseTasksItem",
    "GetWorkflowVersionResponseTasksItemNext",
    "GetWorkflowVersionResponseTriggerEventType",
    "GetWorkflowVersionResponseType",
    "ListWorkflowVersionsResponse",
    "ListWorkflowVersionsResponseResultsItem",
    "ListWorkflowVersionsResponseResultsItemEditor",
    "ListWorkflowVersionsResponseResultsItemEditorId",
    "ListWorkflowVersionsResponseResultsItemTagsItem",
    "ListWorkflowVersionsResponseResultsItemTriggerEventType",
    "ListWorkflowVersionsResponseResultsItemType",
    "UpdateWorkflowRequestTasksItem",
    "UpdateWorkflowRequestTasksItemNext",
    "UpdateWorkflowRequestTriggerEventType",
    "UpdateWorkflowRequestType",
    "UpdateWorkflowResponse",
    "UpdateWorkflowResponseGraph",
    "UpdateWorkflowResponseTagsItem",
    "UpdateWorkflowResponseTasksItem",
    "UpdateWorkflowResponseTasksItemNext",
    "UpdateWorkflowResponseTriggerEventType",
    "UpdateWorkflowResponseType",
    "UpdateWorkflowVersionRequestTasksItem",
    "UpdateWorkflowVersionRequestTasksItemNext",
    "UpdateWorkflowVersionRequestTriggerEventType",
    "UpdateWorkflowVersionRequestType",
    "UpdateWorkflowVersionResponse",
    "UpdateWorkflowVersionResponseGraph",
    "UpdateWorkflowVersionResponseTagsItem",
    "UpdateWorkflowVersionResponseTasksItem",
    "UpdateWorkflowVersionResponseTasksItemNext",
    "UpdateWorkflowVersionResponseTriggerEventType",
    "UpdateWorkflowVersionResponseType",
    "ValidateWorkflowResponse",
    "ValidateWorkflowResponseStatus",
    "ValidateWorkflowResponseTaskResultsItem",
    "ValidateWorkflowResponseTaskResultsItemStatus",
    "ValidateWorkflowResponseValidation",
]
