# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_testset_response_column_definitions_item_type import CreateTestsetResponseColumnDefinitionsItemType


class CreateTestsetResponseColumnDefinitionsItem(UniversalBaseModel):
    field: str = pydantic.Field()
    """
    Canonical field name stored in each row.
    """

    mapped_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional display or import name for this field.
    """

    width: typing.Optional[float] = pydantic.Field(default=None)
    """
    Optional UI width in pixels.
    """

    is_hidden: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this column should be hidden in the UI.
    """

    type: typing.Optional[CreateTestsetResponseColumnDefinitionsItemType] = pydantic.Field(default=None)
    """
    Column value type.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
