# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.public_cached_response_detail import PublicCachedResponseDetail
from ..types.public_cached_response_list import PublicCachedResponseList
from .raw_client import AsyncRawCachesClient, RawCachesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CachesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCachesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCachesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCachesClient
        """
        return self._raw_client

    def retrieve_cached_response(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PublicCachedResponseDetail:
        """
        GET/PATCH/DELETE /api/caches/<cache_key>/ — Retrieve, update, delete by cache_key.
        GET/PATCH/DELETE /api/cache/<id>/ — Legacy alias, lookup by integer PK (JWT only).
        GET/PATCH/DELETE /api/cache/key/<cache_key>/ — Legacy alias, lookup by cache_key.

        JWT auth uses pk lookup when an integer id is supplied; otherwise (and for
        API key auth) lookup is by cache_key_by_org_uuid.

        Parameters
        ----------
        id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicCachedResponseDetail


        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.caches.retrieve_cached_response(
            id=1,
        )
        """
        _response = self._raw_client.retrieve_cached_response(id, request_options=request_options)
        return _response.data

    def filter_cached_responses(
        self,
        *,
        cache_key: typing.Optional[str] = OMIT,
        cache_key_by_org_uuid: typing.Optional[str] = OMIT,
        hit_count: typing.Optional[int] = OMIT,
        timestamp: typing.Optional[dt.datetime] = OMIT,
        updated_at: typing.Optional[dt.datetime] = OMIT,
        expiry_date: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicCachedResponseList:
        """
        POST handler with superadmin-only field protection.

        Strips superadmin-only fields from non-superadmin requests before
        delegating to OrganizationInjectionMixin.post() for org injection.

        Parameters
        ----------
        cache_key : typing.Optional[str]

        cache_key_by_org_uuid : typing.Optional[str]

        hit_count : typing.Optional[int]

        timestamp : typing.Optional[dt.datetime]

        updated_at : typing.Optional[dt.datetime]

        expiry_date : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicCachedResponseList


        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.caches.filter_cached_responses()
        """
        _response = self._raw_client.filter_cached_responses(
            cache_key=cache_key,
            cache_key_by_org_uuid=cache_key_by_org_uuid,
            hit_count=hit_count,
            timestamp=timestamp,
            updated_at=updated_at,
            expiry_date=expiry_date,
            request_options=request_options,
        )
        return _response.data

    def delete_cached_responses(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        DEPRECATED: Batch delete via DELETE /api/caches/ with {"ids": [...]}.
        Use DELETE /api/caches/bulk/ instead. Kept for backward compatibility.
        JWT only — integer IDs are internal and not exposed via API key.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.caches.delete_cached_responses()
        """
        _response = self._raw_client.delete_cached_responses(request_options=request_options)
        return _response.data

    def bulk_delete_cached_responses(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        DELETE /api/caches/bulk/ — Bulk delete cached responses.

        Request body (exactly one of):
            {"ids": [1, 2, 3]}         — JWT only (internal integer PKs)
            {"cache_keys": ["k1","k2"]} — by cache_key_by_org_uuid
            {"all": true}              — deletes all cached responses for the org

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.caches.bulk_delete_cached_responses()
        """
        _response = self._raw_client.bulk_delete_cached_responses(request_options=request_options)
        return _response.data

    def get_filtered_cached_responses_summary(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        POST handler with superadmin-only field protection.

        Strips superadmin-only fields from non-superadmin requests before
        delegating to OrganizationInjectionMixin.post() for org injection.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.caches.get_filtered_cached_responses_summary()
        """
        _response = self._raw_client.get_filtered_cached_responses_summary(request_options=request_options)
        return _response.data


class AsyncCachesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCachesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCachesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCachesClient
        """
        return self._raw_client

    async def retrieve_cached_response(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PublicCachedResponseDetail:
        """
        GET/PATCH/DELETE /api/caches/<cache_key>/ — Retrieve, update, delete by cache_key.
        GET/PATCH/DELETE /api/cache/<id>/ — Legacy alias, lookup by integer PK (JWT only).
        GET/PATCH/DELETE /api/cache/key/<cache_key>/ — Legacy alias, lookup by cache_key.

        JWT auth uses pk lookup when an integer id is supplied; otherwise (and for
        API key auth) lookup is by cache_key_by_org_uuid.

        Parameters
        ----------
        id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicCachedResponseDetail


        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.caches.retrieve_cached_response(
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve_cached_response(id, request_options=request_options)
        return _response.data

    async def filter_cached_responses(
        self,
        *,
        cache_key: typing.Optional[str] = OMIT,
        cache_key_by_org_uuid: typing.Optional[str] = OMIT,
        hit_count: typing.Optional[int] = OMIT,
        timestamp: typing.Optional[dt.datetime] = OMIT,
        updated_at: typing.Optional[dt.datetime] = OMIT,
        expiry_date: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicCachedResponseList:
        """
        POST handler with superadmin-only field protection.

        Strips superadmin-only fields from non-superadmin requests before
        delegating to OrganizationInjectionMixin.post() for org injection.

        Parameters
        ----------
        cache_key : typing.Optional[str]

        cache_key_by_org_uuid : typing.Optional[str]

        hit_count : typing.Optional[int]

        timestamp : typing.Optional[dt.datetime]

        updated_at : typing.Optional[dt.datetime]

        expiry_date : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicCachedResponseList


        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.caches.filter_cached_responses()


        asyncio.run(main())
        """
        _response = await self._raw_client.filter_cached_responses(
            cache_key=cache_key,
            cache_key_by_org_uuid=cache_key_by_org_uuid,
            hit_count=hit_count,
            timestamp=timestamp,
            updated_at=updated_at,
            expiry_date=expiry_date,
            request_options=request_options,
        )
        return _response.data

    async def delete_cached_responses(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        DEPRECATED: Batch delete via DELETE /api/caches/ with {"ids": [...]}.
        Use DELETE /api/caches/bulk/ instead. Kept for backward compatibility.
        JWT only — integer IDs are internal and not exposed via API key.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.caches.delete_cached_responses()


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_cached_responses(request_options=request_options)
        return _response.data

    async def bulk_delete_cached_responses(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        DELETE /api/caches/bulk/ — Bulk delete cached responses.

        Request body (exactly one of):
            {"ids": [1, 2, 3]}         — JWT only (internal integer PKs)
            {"cache_keys": ["k1","k2"]} — by cache_key_by_org_uuid
            {"all": true}              — deletes all cached responses for the org

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.caches.bulk_delete_cached_responses()


        asyncio.run(main())
        """
        _response = await self._raw_client.bulk_delete_cached_responses(request_options=request_options)
        return _response.data

    async def get_filtered_cached_responses_summary(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        POST handler with superadmin-only field protection.

        Strips superadmin-only fields from non-superadmin requests before
        delegating to OrganizationInjectionMixin.post() for org injection.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.caches.get_filtered_cached_responses_summary()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_filtered_cached_responses_summary(request_options=request_options)
        return _response.data
