# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawTestsetsClient, RawTestsetsClient
from .types.create_testset_request_column_definitions_item import CreateTestsetRequestColumnDefinitionsItem
from .types.create_testset_response import CreateTestsetResponse
from .types.create_testset_rows_request_body_item import CreateTestsetRowsRequestBodyItem
from .types.create_testset_rows_response import CreateTestsetRowsResponse
from .types.list_testset_rows_response import ListTestsetRowsResponse
from .types.list_testsets_response import ListTestsetsResponse
from .types.retrieve_testset_response import RetrieveTestsetResponse
from .types.update_testset_response import UpdateTestsetResponse
from .types.update_testset_row_response import UpdateTestsetRowResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TestsetsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTestsetsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTestsetsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTestsetsClient
        """
        return self._raw_client

    def create_testset(
        self,
        *,
        authorization: str,
        name: str,
        description: typing.Optional[str] = OMIT,
        column_definitions: typing.Optional[typing.Sequence[CreateTestsetRequestColumnDefinitionsItem]] = OMIT,
        starred: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateTestsetResponse:
        """
        Create a new testset for evaluation.

        Parameters
        ----------
        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        name : str
            Testset name.

        description : typing.Optional[str]
            Testset description.

        column_definitions : typing.Optional[typing.Sequence[CreateTestsetRequestColumnDefinitionsItem]]
            Column definitions for the testset.

        starred : typing.Optional[bool]
            Star the testset.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateTestsetResponse
            Created testset.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient()
        client.testsets.create_testset(
            authorization="Bearer sk_live_xxxxx",
            name="QA Test Set",
        )
        """
        _response = self._raw_client.create_testset(
            authorization=authorization,
            name=name,
            description=description,
            column_definitions=column_definitions,
            starred=starred,
            request_options=request_options,
        )
        return _response.data

    def list_testsets(
        self,
        *,
        authorization: str,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListTestsetsResponse:
        """
        List testsets with optional filtering.

        Parameters
        ----------
        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Filter criteria.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListTestsetsResponse
            List of testsets.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient()
        client.testsets.list_testsets(
            authorization="Bearer sk_live_xxxxx",
        )
        """
        _response = self._raw_client.list_testsets(
            authorization=authorization, filters=filters, request_options=request_options
        )
        return _response.data

    def retrieve_testset(
        self, testset_id: str, *, authorization: str, request_options: typing.Optional[RequestOptions] = None
    ) -> RetrieveTestsetResponse:
        """
        Retrieve a testset by ID, including column definitions.

        Parameters
        ----------
        testset_id : str
            The ID of the testset to retrieve.

        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetrieveTestsetResponse
            Testset details.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient()
        client.testsets.retrieve_testset(
            testset_id="testset_id",
            authorization="Bearer sk_live_xxxxx",
        )
        """
        _response = self._raw_client.retrieve_testset(
            testset_id, authorization=authorization, request_options=request_options
        )
        return _response.data

    def delete_testset(
        self, testset_id: str, *, authorization: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Delete a testset and all its rows.

        Parameters
        ----------
        testset_id : str
            The ID of the testset to delete.

        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from respan import RespanClient

        client = RespanClient()
        client.testsets.delete_testset(
            testset_id="testset_id",
            authorization="Bearer sk_live_xxxxx",
        )
        """
        _response = self._raw_client.delete_testset(
            testset_id, authorization=authorization, request_options=request_options
        )
        return _response.data

    def update_testset(
        self,
        testset_id: str,
        *,
        authorization: str,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        starred: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateTestsetResponse:
        """
        Update a testset's name, description, or starred status.

        Parameters
        ----------
        testset_id : str
            The ID of the testset to update.

        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        name : typing.Optional[str]
            Testset name.

        description : typing.Optional[str]
            Testset description.

        starred : typing.Optional[bool]
            Star the testset.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateTestsetResponse
            Updated testset.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient()
        client.testsets.update_testset(
            testset_id="testset_id",
            authorization="Bearer sk_live_xxxxx",
        )
        """
        _response = self._raw_client.update_testset(
            testset_id,
            authorization=authorization,
            name=name,
            description=description,
            starred=starred,
            request_options=request_options,
        )
        return _response.data

    def list_testset_rows(
        self, testset_id: str, *, authorization: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ListTestsetRowsResponse:
        """
        List all rows in a testset.

        Parameters
        ----------
        testset_id : str
            The ID of the testset to list rows from.

        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListTestsetRowsResponse
            List of rows.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient()
        client.testsets.list_testset_rows(
            testset_id="testset_id",
            authorization="Bearer sk_live_xxxxx",
        )
        """
        _response = self._raw_client.list_testset_rows(
            testset_id, authorization=authorization, request_options=request_options
        )
        return _response.data

    def create_testset_rows(
        self,
        testset_id: str,
        *,
        authorization: str,
        request: typing.Sequence[CreateTestsetRowsRequestBodyItem],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateTestsetRowsResponse:
        """
        Add rows to a testset.

        Parameters
        ----------
        testset_id : str
            The ID of the testset to add rows to.

        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        request : typing.Sequence[CreateTestsetRowsRequestBodyItem]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateTestsetRowsResponse
            Created rows.

        Examples
        --------
        from respan import RespanClient
        from respan.testsets import CreateTestsetRowsRequestBodyItem

        client = RespanClient()
        client.testsets.create_testset_rows(
            testset_id="testset_id",
            authorization="Bearer sk_live_xxxxx",
            request=[CreateTestsetRowsRequestBodyItem()],
        )
        """
        _response = self._raw_client.create_testset_rows(
            testset_id, authorization=authorization, request=request, request_options=request_options
        )
        return _response.data

    def delete_testset_row(
        self,
        testset_id: str,
        row_index: int,
        *,
        authorization: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Delete a specific row from a testset.

        Parameters
        ----------
        testset_id : str
            The ID of the testset.

        row_index : int
            The index of the row to delete.

        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from respan import RespanClient

        client = RespanClient()
        client.testsets.delete_testset_row(
            testset_id="testset_id",
            row_index=1,
            authorization="Bearer sk_live_xxxxx",
        )
        """
        _response = self._raw_client.delete_testset_row(
            testset_id, row_index, authorization=authorization, request_options=request_options
        )
        return _response.data

    def update_testset_row(
        self,
        testset_id: str,
        row_index: int,
        *,
        authorization: str,
        row_data: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateTestsetRowResponse:
        """
        Update a specific row in a testset.

        Parameters
        ----------
        testset_id : str
            The ID of the testset.

        row_index : int
            The index of the row to update.

        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        row_data : typing.Optional[typing.Dict[str, typing.Any]]
            Updated row data keyed by column name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateTestsetRowResponse
            Updated row.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient()
        client.testsets.update_testset_row(
            testset_id="testset_id",
            row_index=1,
            authorization="Bearer sk_live_xxxxx",
        )
        """
        _response = self._raw_client.update_testset_row(
            testset_id, row_index, authorization=authorization, row_data=row_data, request_options=request_options
        )
        return _response.data


class AsyncTestsetsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTestsetsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTestsetsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTestsetsClient
        """
        return self._raw_client

    async def create_testset(
        self,
        *,
        authorization: str,
        name: str,
        description: typing.Optional[str] = OMIT,
        column_definitions: typing.Optional[typing.Sequence[CreateTestsetRequestColumnDefinitionsItem]] = OMIT,
        starred: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateTestsetResponse:
        """
        Create a new testset for evaluation.

        Parameters
        ----------
        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        name : str
            Testset name.

        description : typing.Optional[str]
            Testset description.

        column_definitions : typing.Optional[typing.Sequence[CreateTestsetRequestColumnDefinitionsItem]]
            Column definitions for the testset.

        starred : typing.Optional[bool]
            Star the testset.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateTestsetResponse
            Created testset.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient()


        async def main() -> None:
            await client.testsets.create_testset(
                authorization="Bearer sk_live_xxxxx",
                name="QA Test Set",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_testset(
            authorization=authorization,
            name=name,
            description=description,
            column_definitions=column_definitions,
            starred=starred,
            request_options=request_options,
        )
        return _response.data

    async def list_testsets(
        self,
        *,
        authorization: str,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListTestsetsResponse:
        """
        List testsets with optional filtering.

        Parameters
        ----------
        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Filter criteria.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListTestsetsResponse
            List of testsets.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient()


        async def main() -> None:
            await client.testsets.list_testsets(
                authorization="Bearer sk_live_xxxxx",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_testsets(
            authorization=authorization, filters=filters, request_options=request_options
        )
        return _response.data

    async def retrieve_testset(
        self, testset_id: str, *, authorization: str, request_options: typing.Optional[RequestOptions] = None
    ) -> RetrieveTestsetResponse:
        """
        Retrieve a testset by ID, including column definitions.

        Parameters
        ----------
        testset_id : str
            The ID of the testset to retrieve.

        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetrieveTestsetResponse
            Testset details.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient()


        async def main() -> None:
            await client.testsets.retrieve_testset(
                testset_id="testset_id",
                authorization="Bearer sk_live_xxxxx",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve_testset(
            testset_id, authorization=authorization, request_options=request_options
        )
        return _response.data

    async def delete_testset(
        self, testset_id: str, *, authorization: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Delete a testset and all its rows.

        Parameters
        ----------
        testset_id : str
            The ID of the testset to delete.

        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient()


        async def main() -> None:
            await client.testsets.delete_testset(
                testset_id="testset_id",
                authorization="Bearer sk_live_xxxxx",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_testset(
            testset_id, authorization=authorization, request_options=request_options
        )
        return _response.data

    async def update_testset(
        self,
        testset_id: str,
        *,
        authorization: str,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        starred: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateTestsetResponse:
        """
        Update a testset's name, description, or starred status.

        Parameters
        ----------
        testset_id : str
            The ID of the testset to update.

        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        name : typing.Optional[str]
            Testset name.

        description : typing.Optional[str]
            Testset description.

        starred : typing.Optional[bool]
            Star the testset.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateTestsetResponse
            Updated testset.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient()


        async def main() -> None:
            await client.testsets.update_testset(
                testset_id="testset_id",
                authorization="Bearer sk_live_xxxxx",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_testset(
            testset_id,
            authorization=authorization,
            name=name,
            description=description,
            starred=starred,
            request_options=request_options,
        )
        return _response.data

    async def list_testset_rows(
        self, testset_id: str, *, authorization: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ListTestsetRowsResponse:
        """
        List all rows in a testset.

        Parameters
        ----------
        testset_id : str
            The ID of the testset to list rows from.

        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListTestsetRowsResponse
            List of rows.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient()


        async def main() -> None:
            await client.testsets.list_testset_rows(
                testset_id="testset_id",
                authorization="Bearer sk_live_xxxxx",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_testset_rows(
            testset_id, authorization=authorization, request_options=request_options
        )
        return _response.data

    async def create_testset_rows(
        self,
        testset_id: str,
        *,
        authorization: str,
        request: typing.Sequence[CreateTestsetRowsRequestBodyItem],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateTestsetRowsResponse:
        """
        Add rows to a testset.

        Parameters
        ----------
        testset_id : str
            The ID of the testset to add rows to.

        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        request : typing.Sequence[CreateTestsetRowsRequestBodyItem]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateTestsetRowsResponse
            Created rows.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient
        from respan.testsets import CreateTestsetRowsRequestBodyItem

        client = AsyncRespanClient()


        async def main() -> None:
            await client.testsets.create_testset_rows(
                testset_id="testset_id",
                authorization="Bearer sk_live_xxxxx",
                request=[CreateTestsetRowsRequestBodyItem()],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_testset_rows(
            testset_id, authorization=authorization, request=request, request_options=request_options
        )
        return _response.data

    async def delete_testset_row(
        self,
        testset_id: str,
        row_index: int,
        *,
        authorization: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Delete a specific row from a testset.

        Parameters
        ----------
        testset_id : str
            The ID of the testset.

        row_index : int
            The index of the row to delete.

        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient()


        async def main() -> None:
            await client.testsets.delete_testset_row(
                testset_id="testset_id",
                row_index=1,
                authorization="Bearer sk_live_xxxxx",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_testset_row(
            testset_id, row_index, authorization=authorization, request_options=request_options
        )
        return _response.data

    async def update_testset_row(
        self,
        testset_id: str,
        row_index: int,
        *,
        authorization: str,
        row_data: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateTestsetRowResponse:
        """
        Update a specific row in a testset.

        Parameters
        ----------
        testset_id : str
            The ID of the testset.

        row_index : int
            The index of the row to update.

        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        row_data : typing.Optional[typing.Dict[str, typing.Any]]
            Updated row data keyed by column name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateTestsetRowResponse
            Updated row.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient()


        async def main() -> None:
            await client.testsets.update_testset_row(
                testset_id="testset_id",
                row_index=1,
                authorization="Bearer sk_live_xxxxx",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_testset_row(
            testset_id, row_index, authorization=authorization, row_data=row_data, request_options=request_options
        )
        return _response.data
