# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawCreditTransactionsClient, RawCreditTransactionsClient
from .types.list_credit_transactions_response import ListCreditTransactionsResponse
from .types.list_credit_transactions_response_results_item import ListCreditTransactionsResponseResultsItem
from .types.retrieve_credit_transaction_response import RetrieveCreditTransactionResponse


class CreditTransactionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCreditTransactionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCreditTransactionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCreditTransactionsClient
        """
        return self._raw_client

    def list_credit_transactions(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[ListCreditTransactionsResponseResultsItem, ListCreditTransactionsResponse]:
        """
        List credit transactions with pagination.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number for pagination.

        page_size : typing.Optional[int]
            Number of items per page. Maximum is 1000.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[ListCreditTransactionsResponseResultsItem, ListCreditTransactionsResponse]
            Paginated list of transactions.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )
        response = client.credit_transactions.list_credit_transactions()
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_credit_transactions(
            page=page, page_size=page_size, request_options=request_options
        )

    def retrieve_credit_transaction(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RetrieveCreditTransactionResponse:
        """
        Retrieve details of a specific credit transaction.

        Parameters
        ----------
        id : str
            The unique identifier of the transaction to retrieve (e.g., ct_1a2b3c4d5e6f7g8h)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetrieveCreditTransactionResponse
            Transaction details.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )
        client.credit_transactions.retrieve_credit_transaction(
            id="id",
        )
        """
        _response = self._raw_client.retrieve_credit_transaction(id, request_options=request_options)
        return _response.data


class AsyncCreditTransactionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCreditTransactionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCreditTransactionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCreditTransactionsClient
        """
        return self._raw_client

    async def list_credit_transactions(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[ListCreditTransactionsResponseResultsItem, ListCreditTransactionsResponse]:
        """
        List credit transactions with pagination.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number for pagination.

        page_size : typing.Optional[int]
            Number of items per page. Maximum is 1000.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[ListCreditTransactionsResponseResultsItem, ListCreditTransactionsResponse]
            Paginated list of transactions.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )


        async def main() -> None:
            response = await client.credit_transactions.list_credit_transactions()
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_credit_transactions(
            page=page, page_size=page_size, request_options=request_options
        )

    async def retrieve_credit_transaction(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RetrieveCreditTransactionResponse:
        """
        Retrieve details of a specific credit transaction.

        Parameters
        ----------
        id : str
            The unique identifier of the transaction to retrieve (e.g., ct_1a2b3c4d5e6f7g8h)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetrieveCreditTransactionResponse
            Transaction details.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )


        async def main() -> None:
            await client.credit_transactions.retrieve_credit_transaction(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve_credit_transaction(id, request_options=request_options)
        return _response.data
