# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .commit_prompt_version_response_edited_by import CommitPromptVersionResponseEditedBy


class CommitPromptVersionResponse(UniversalBaseModel):
    id: typing.Optional[str] = None
    prompt_version_id: typing.Optional[str] = None
    version: typing.Optional[int] = None
    description: typing.Optional[str] = None
    messages: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = None
    model: typing.Optional[str] = None
    readonly: typing.Optional[bool] = None
    is_deployed: typing.Optional[bool] = None
    edited_by: typing.Optional[CommitPromptVersionResponseEditedBy] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
