# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .threads_list_response_results_item import ThreadsListResponseResultsItem


class ThreadsListResponse(UniversalBaseModel):
    count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total matching threads.
    """

    next: typing.Optional[str] = pydantic.Field(default=None)
    """
    Next page URL.
    """

    previous: typing.Optional[str] = pydantic.Field(default=None)
    """
    Previous page URL.
    """

    results: typing.Optional[typing.List[ThreadsListResponseResultsItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
