# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.datetime_utils import serialize_datetime
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..types.activity_create import ActivityCreate
from ..types.activity_summary_response import ActivitySummaryResponse
from ..types.activity_type_enum import ActivityTypeEnum
from ..types.activity_update import ActivityUpdate
from ..types.paginated_activity_list_list import PaginatedActivityListList
from ..types.paginated_object_interaction_list import PaginatedObjectInteractionList
from .types.api_activities_object_interactions_filtered_request_sort_by import (
    ApiActivitiesObjectInteractionsFilteredRequestSortBy,
)
from .types.api_activities_object_interactions_request_sort_by import ApiActivitiesObjectInteractionsRequestSortBy

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawActivitiesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def api_activities_feature_list(
        self,
        feature_type: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaginatedActivityListList]:
        """
        Cross-object activity list for a feature_type.

        Parameters
        ----------
        feature_type : str

        page : typing.Optional[int]
            A page number within the paginated result set.

        page_size : typing.Optional[int]
            Number of results to return per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaginatedActivityListList]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/list/",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedActivityListList,
                    parse_obj_as(
                        type_=PaginatedActivityListList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_activities_objects_create(
        self,
        feature_type: str,
        object_id: str,
        *,
        activity_type: ActivityTypeEnum,
        message: typing.Optional[str] = OMIT,
        version_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ActivityCreate]:
        """
        POST handler with superadmin-only field protection.

        Strips superadmin-only fields from non-superadmin requests before
        delegating to OrganizationInjectionMixin.post() for org injection.

        Parameters
        ----------
        feature_type : str

        object_id : str

        activity_type : ActivityTypeEnum

        message : typing.Optional[str]

        version_id : typing.Optional[str]
            Optional version reference (prompt_version id, workflow_version id)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ActivityCreate]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/",
            method="POST",
            json={
                "activity_type": activity_type,
                "message": message,
                "version_id": version_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ActivityCreate,
                    parse_obj_as(
                        type_=ActivityCreate,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_activities_objects_retrieve(
        self, feature_type: str, object_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Retrieve, update, or delete a single activity.

        GET    /api/activities/<feature_type>/objects/<object_id>/<pk>/
        PATCH  /api/activities/<feature_type>/objects/<object_id>/<pk>/ — Edit comment message.
        DELETE /api/activities/<feature_type>/objects/<object_id>/<pk>/ — Delete comment.

        Only comment activities can be modified or deleted.

        Parameters
        ----------
        feature_type : str

        object_id : str

        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/{jsonable_encoder(id)}/",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_activities_objects_create2(
        self, feature_type: str, object_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        POST handler with superadmin-only field protection.

        Strips superadmin-only fields from non-superadmin requests before
        delegating to OrganizationInjectionMixin.post() for org injection.

        Parameters
        ----------
        feature_type : str

        object_id : str

        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/{jsonable_encoder(id)}/",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_activities_objects_update(
        self,
        feature_type: str,
        object_id: str,
        id: str,
        *,
        message: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ActivityUpdate]:
        """
        PUT handler with superadmin lock and field protection.

        Same as patch() - checks lock and field protection before delegating.

        Parameters
        ----------
        feature_type : str

        object_id : str

        id : str

        message : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ActivityUpdate]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/{jsonable_encoder(id)}/",
            method="PUT",
            json={
                "message": message,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ActivityUpdate,
                    parse_obj_as(
                        type_=ActivityUpdate,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_activities_objects_destroy(
        self, feature_type: str, object_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Retrieve, update, or delete a single activity.

        GET    /api/activities/<feature_type>/objects/<object_id>/<pk>/
        PATCH  /api/activities/<feature_type>/objects/<object_id>/<pk>/ — Edit comment message.
        DELETE /api/activities/<feature_type>/objects/<object_id>/<pk>/ — Delete comment.

        Only comment activities can be modified or deleted.

        Parameters
        ----------
        feature_type : str

        object_id : str

        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/{jsonable_encoder(id)}/",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_activities_objects_partial_update(
        self,
        feature_type: str,
        object_id: str,
        id: str,
        *,
        message: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ActivityUpdate]:
        """
        PATCH handler with superadmin lock and field protection.

        Checks:
        1. Object lock (is_managed=True -> non-superadmins can't modify)
        2. Field protection (non-superadmins can't modify specific fields)

        Parameters
        ----------
        feature_type : str

        object_id : str

        id : str

        message : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ActivityUpdate]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/{jsonable_encoder(id)}/",
            method="PATCH",
            json={
                "message": message,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ActivityUpdate,
                    parse_obj_as(
                        type_=ActivityUpdate,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_activities_objects_list_retrieve(
        self, feature_type: str, object_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        List activities for a resource.

        GET  /api/activities/<feature_type>/objects/<object_id>/list/
        POST /api/activities/<feature_type>/objects/<object_id>/list/ — POST-for-filtering.

        Parameters
        ----------
        feature_type : str

        object_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/list/",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_activities_list_filtered(
        self,
        feature_type: str,
        object_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaginatedActivityListList]:
        """
        List activities with complex filtering via POST body.

        Parameters
        ----------
        feature_type : str

        object_id : str

        page : typing.Optional[int]
            A page number within the paginated result set.

        page_size : typing.Optional[int]
            Number of results to return per page.

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Filter parameters keyed by field name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaginatedActivityListList]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/list/",
            method="POST",
            params={
                "page": page,
                "page_size": page_size,
            },
            json={
                "filters": filters,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedActivityListList,
                    parse_obj_as(
                        type_=PaginatedActivityListList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_activities_objects_summary_retrieve(
        self, feature_type: str, object_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ActivitySummaryResponse]:
        """
        Count activities for a resource.

        GET /api/activities/<feature_type>/objects/<object_id>/summary/
        Returns: { total_count }

        Parameters
        ----------
        feature_type : str

        object_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ActivitySummaryResponse]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/summary/",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ActivitySummaryResponse,
                    parse_obj_as(
                        type_=ActivitySummaryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_activities_org_list(
        self,
        *,
        feature_type: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaginatedActivityListList]:
        """
        Org-wide activity stream across all feature types the caller can read, newest first. Optional ?feature_type= restricts to one kind.

        Parameters
        ----------
        feature_type : typing.Optional[str]
            Restrict the stream to one resource kind. Unknown values return 400; a kind the caller cannot read returns 403.

        page : typing.Optional[int]
            A page number within the paginated result set.

        page_size : typing.Optional[int]
            Number of results to return per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaginatedActivityListList]

        """
        _response = self._client_wrapper.httpx_client.request(
            "api/activities/list/",
            method="GET",
            params={
                "feature_type": feature_type,
                "page": page,
                "page_size": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedActivityListList,
                    parse_obj_as(
                        type_=PaginatedActivityListList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_activities_object_interactions(
        self,
        *,
        date: typing.Optional[dt.date] = None,
        end_time: typing.Optional[dt.datetime] = None,
        feature_type: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort_by: typing.Optional[ApiActivitiesObjectInteractionsRequestSortBy] = None,
        start_time: typing.Optional[dt.datetime] = None,
        summary_type: typing.Optional[str] = None,
        timezone_offset: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaginatedObjectInteractionList]:
        """
        The requesting user's object-interaction aggregates (sortable, paged). One row per object the caller has opened, with interaction_count, last_interaction_at, and the display name. Dashboard (JWT) identity only — API-key requests receive an empty page. Also accepts the standard dashboard time-window params (start_time / end_time / date / summary_type / timezone_offset; default last 30 days).

        Parameters
        ----------
        date : typing.Optional[dt.date]
            Anchor date (ISO 8601) for the summary_type window.

        end_time : typing.Optional[dt.datetime]
            Window end (ISO 8601).

        feature_type : typing.Optional[str]
            Restrict to one resource kind (e.g. datasets, prompts). Omitted returns a mixed cross-feature list. Unknown values return 400.

        page : typing.Optional[int]
            A page number within the paginated result set.

        page_size : typing.Optional[int]
            Number of results to return per page.

        sort_by : typing.Optional[ApiActivitiesObjectInteractionsRequestSortBy]
            Sort key, '-'-prefixed for descending. Default is recency (-last_interaction_at); -interaction_count serves a most-visited view. Unknown values fall back to the default.

        start_time : typing.Optional[dt.datetime]
            Window start (ISO 8601). Overrides the summary_type/date window.

        summary_type : typing.Optional[str]
            Named window preset resolved relative to `date` (default: all).

        timezone_offset : typing.Optional[float]
            Hours of UTC-minus-local offset used to resolve day boundaries.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaginatedObjectInteractionList]

        """
        _response = self._client_wrapper.httpx_client.request(
            "api/activities/object-interactions/",
            method="GET",
            params={
                "date": str(date) if date is not None else None,
                "end_time": serialize_datetime(end_time) if end_time is not None else None,
                "feature_type": feature_type,
                "page": page,
                "page_size": page_size,
                "sort_by": sort_by,
                "start_time": serialize_datetime(start_time) if start_time is not None else None,
                "summary_type": summary_type,
                "timezone_offset": timezone_offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedObjectInteractionList,
                    parse_obj_as(
                        type_=PaginatedObjectInteractionList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_activities_object_interactions_filtered(
        self,
        *,
        date: typing.Optional[dt.date] = None,
        end_time: typing.Optional[dt.datetime] = None,
        feature_type: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort_by: typing.Optional[ApiActivitiesObjectInteractionsFilteredRequestSortBy] = None,
        start_time: typing.Optional[dt.datetime] = None,
        summary_type: typing.Optional[str] = None,
        timezone_offset: typing.Optional[float] = None,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaginatedObjectInteractionList]:
        """
        List object-interaction aggregates with complex filtering via POST body (POST-for-filtering — NOT a create). Scalar params stay in the query string exactly as on GET; the response is identical to the equivalent GET.

        Parameters
        ----------
        date : typing.Optional[dt.date]
            Anchor date (ISO 8601) for the summary_type window.

        end_time : typing.Optional[dt.datetime]
            Window end (ISO 8601).

        feature_type : typing.Optional[str]
            Restrict to one resource kind (e.g. datasets, prompts). Omitted returns a mixed cross-feature list. Unknown values return 400.

        page : typing.Optional[int]
            A page number within the paginated result set.

        page_size : typing.Optional[int]
            Number of results to return per page.

        sort_by : typing.Optional[ApiActivitiesObjectInteractionsFilteredRequestSortBy]
            Sort key, '-'-prefixed for descending. Default is recency (-last_interaction_at); -interaction_count serves a most-visited view. Unknown values fall back to the default.

        start_time : typing.Optional[dt.datetime]
            Window start (ISO 8601). Overrides the summary_type/date window.

        summary_type : typing.Optional[str]
            Named window preset resolved relative to `date` (default: all).

        timezone_offset : typing.Optional[float]
            Hours of UTC-minus-local offset used to resolve day boundaries.

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Filter parameters keyed by field name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaginatedObjectInteractionList]

        """
        _response = self._client_wrapper.httpx_client.request(
            "api/activities/object-interactions/",
            method="POST",
            params={
                "date": str(date) if date is not None else None,
                "end_time": serialize_datetime(end_time) if end_time is not None else None,
                "feature_type": feature_type,
                "page": page,
                "page_size": page_size,
                "sort_by": sort_by,
                "start_time": serialize_datetime(start_time) if start_time is not None else None,
                "summary_type": summary_type,
                "timezone_offset": timezone_offset,
            },
            json={
                "filters": filters,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedObjectInteractionList,
                    parse_obj_as(
                        type_=PaginatedObjectInteractionList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawActivitiesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def api_activities_feature_list(
        self,
        feature_type: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaginatedActivityListList]:
        """
        Cross-object activity list for a feature_type.

        Parameters
        ----------
        feature_type : str

        page : typing.Optional[int]
            A page number within the paginated result set.

        page_size : typing.Optional[int]
            Number of results to return per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaginatedActivityListList]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/list/",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedActivityListList,
                    parse_obj_as(
                        type_=PaginatedActivityListList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_activities_objects_create(
        self,
        feature_type: str,
        object_id: str,
        *,
        activity_type: ActivityTypeEnum,
        message: typing.Optional[str] = OMIT,
        version_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ActivityCreate]:
        """
        POST handler with superadmin-only field protection.

        Strips superadmin-only fields from non-superadmin requests before
        delegating to OrganizationInjectionMixin.post() for org injection.

        Parameters
        ----------
        feature_type : str

        object_id : str

        activity_type : ActivityTypeEnum

        message : typing.Optional[str]

        version_id : typing.Optional[str]
            Optional version reference (prompt_version id, workflow_version id)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ActivityCreate]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/",
            method="POST",
            json={
                "activity_type": activity_type,
                "message": message,
                "version_id": version_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ActivityCreate,
                    parse_obj_as(
                        type_=ActivityCreate,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_activities_objects_retrieve(
        self, feature_type: str, object_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Retrieve, update, or delete a single activity.

        GET    /api/activities/<feature_type>/objects/<object_id>/<pk>/
        PATCH  /api/activities/<feature_type>/objects/<object_id>/<pk>/ — Edit comment message.
        DELETE /api/activities/<feature_type>/objects/<object_id>/<pk>/ — Delete comment.

        Only comment activities can be modified or deleted.

        Parameters
        ----------
        feature_type : str

        object_id : str

        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/{jsonable_encoder(id)}/",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_activities_objects_create2(
        self, feature_type: str, object_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        POST handler with superadmin-only field protection.

        Strips superadmin-only fields from non-superadmin requests before
        delegating to OrganizationInjectionMixin.post() for org injection.

        Parameters
        ----------
        feature_type : str

        object_id : str

        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/{jsonable_encoder(id)}/",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_activities_objects_update(
        self,
        feature_type: str,
        object_id: str,
        id: str,
        *,
        message: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ActivityUpdate]:
        """
        PUT handler with superadmin lock and field protection.

        Same as patch() - checks lock and field protection before delegating.

        Parameters
        ----------
        feature_type : str

        object_id : str

        id : str

        message : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ActivityUpdate]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/{jsonable_encoder(id)}/",
            method="PUT",
            json={
                "message": message,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ActivityUpdate,
                    parse_obj_as(
                        type_=ActivityUpdate,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_activities_objects_destroy(
        self, feature_type: str, object_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Retrieve, update, or delete a single activity.

        GET    /api/activities/<feature_type>/objects/<object_id>/<pk>/
        PATCH  /api/activities/<feature_type>/objects/<object_id>/<pk>/ — Edit comment message.
        DELETE /api/activities/<feature_type>/objects/<object_id>/<pk>/ — Delete comment.

        Only comment activities can be modified or deleted.

        Parameters
        ----------
        feature_type : str

        object_id : str

        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/{jsonable_encoder(id)}/",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_activities_objects_partial_update(
        self,
        feature_type: str,
        object_id: str,
        id: str,
        *,
        message: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ActivityUpdate]:
        """
        PATCH handler with superadmin lock and field protection.

        Checks:
        1. Object lock (is_managed=True -> non-superadmins can't modify)
        2. Field protection (non-superadmins can't modify specific fields)

        Parameters
        ----------
        feature_type : str

        object_id : str

        id : str

        message : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ActivityUpdate]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/{jsonable_encoder(id)}/",
            method="PATCH",
            json={
                "message": message,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ActivityUpdate,
                    parse_obj_as(
                        type_=ActivityUpdate,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_activities_objects_list_retrieve(
        self, feature_type: str, object_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        List activities for a resource.

        GET  /api/activities/<feature_type>/objects/<object_id>/list/
        POST /api/activities/<feature_type>/objects/<object_id>/list/ — POST-for-filtering.

        Parameters
        ----------
        feature_type : str

        object_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/list/",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_activities_list_filtered(
        self,
        feature_type: str,
        object_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaginatedActivityListList]:
        """
        List activities with complex filtering via POST body.

        Parameters
        ----------
        feature_type : str

        object_id : str

        page : typing.Optional[int]
            A page number within the paginated result set.

        page_size : typing.Optional[int]
            Number of results to return per page.

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Filter parameters keyed by field name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaginatedActivityListList]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/list/",
            method="POST",
            params={
                "page": page,
                "page_size": page_size,
            },
            json={
                "filters": filters,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedActivityListList,
                    parse_obj_as(
                        type_=PaginatedActivityListList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_activities_objects_summary_retrieve(
        self, feature_type: str, object_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ActivitySummaryResponse]:
        """
        Count activities for a resource.

        GET /api/activities/<feature_type>/objects/<object_id>/summary/
        Returns: { total_count }

        Parameters
        ----------
        feature_type : str

        object_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ActivitySummaryResponse]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/activities/{jsonable_encoder(feature_type)}/objects/{jsonable_encoder(object_id)}/summary/",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ActivitySummaryResponse,
                    parse_obj_as(
                        type_=ActivitySummaryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_activities_org_list(
        self,
        *,
        feature_type: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaginatedActivityListList]:
        """
        Org-wide activity stream across all feature types the caller can read, newest first. Optional ?feature_type= restricts to one kind.

        Parameters
        ----------
        feature_type : typing.Optional[str]
            Restrict the stream to one resource kind. Unknown values return 400; a kind the caller cannot read returns 403.

        page : typing.Optional[int]
            A page number within the paginated result set.

        page_size : typing.Optional[int]
            Number of results to return per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaginatedActivityListList]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/activities/list/",
            method="GET",
            params={
                "feature_type": feature_type,
                "page": page,
                "page_size": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedActivityListList,
                    parse_obj_as(
                        type_=PaginatedActivityListList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_activities_object_interactions(
        self,
        *,
        date: typing.Optional[dt.date] = None,
        end_time: typing.Optional[dt.datetime] = None,
        feature_type: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort_by: typing.Optional[ApiActivitiesObjectInteractionsRequestSortBy] = None,
        start_time: typing.Optional[dt.datetime] = None,
        summary_type: typing.Optional[str] = None,
        timezone_offset: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaginatedObjectInteractionList]:
        """
        The requesting user's object-interaction aggregates (sortable, paged). One row per object the caller has opened, with interaction_count, last_interaction_at, and the display name. Dashboard (JWT) identity only — API-key requests receive an empty page. Also accepts the standard dashboard time-window params (start_time / end_time / date / summary_type / timezone_offset; default last 30 days).

        Parameters
        ----------
        date : typing.Optional[dt.date]
            Anchor date (ISO 8601) for the summary_type window.

        end_time : typing.Optional[dt.datetime]
            Window end (ISO 8601).

        feature_type : typing.Optional[str]
            Restrict to one resource kind (e.g. datasets, prompts). Omitted returns a mixed cross-feature list. Unknown values return 400.

        page : typing.Optional[int]
            A page number within the paginated result set.

        page_size : typing.Optional[int]
            Number of results to return per page.

        sort_by : typing.Optional[ApiActivitiesObjectInteractionsRequestSortBy]
            Sort key, '-'-prefixed for descending. Default is recency (-last_interaction_at); -interaction_count serves a most-visited view. Unknown values fall back to the default.

        start_time : typing.Optional[dt.datetime]
            Window start (ISO 8601). Overrides the summary_type/date window.

        summary_type : typing.Optional[str]
            Named window preset resolved relative to `date` (default: all).

        timezone_offset : typing.Optional[float]
            Hours of UTC-minus-local offset used to resolve day boundaries.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaginatedObjectInteractionList]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/activities/object-interactions/",
            method="GET",
            params={
                "date": str(date) if date is not None else None,
                "end_time": serialize_datetime(end_time) if end_time is not None else None,
                "feature_type": feature_type,
                "page": page,
                "page_size": page_size,
                "sort_by": sort_by,
                "start_time": serialize_datetime(start_time) if start_time is not None else None,
                "summary_type": summary_type,
                "timezone_offset": timezone_offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedObjectInteractionList,
                    parse_obj_as(
                        type_=PaginatedObjectInteractionList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_activities_object_interactions_filtered(
        self,
        *,
        date: typing.Optional[dt.date] = None,
        end_time: typing.Optional[dt.datetime] = None,
        feature_type: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort_by: typing.Optional[ApiActivitiesObjectInteractionsFilteredRequestSortBy] = None,
        start_time: typing.Optional[dt.datetime] = None,
        summary_type: typing.Optional[str] = None,
        timezone_offset: typing.Optional[float] = None,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaginatedObjectInteractionList]:
        """
        List object-interaction aggregates with complex filtering via POST body (POST-for-filtering — NOT a create). Scalar params stay in the query string exactly as on GET; the response is identical to the equivalent GET.

        Parameters
        ----------
        date : typing.Optional[dt.date]
            Anchor date (ISO 8601) for the summary_type window.

        end_time : typing.Optional[dt.datetime]
            Window end (ISO 8601).

        feature_type : typing.Optional[str]
            Restrict to one resource kind (e.g. datasets, prompts). Omitted returns a mixed cross-feature list. Unknown values return 400.

        page : typing.Optional[int]
            A page number within the paginated result set.

        page_size : typing.Optional[int]
            Number of results to return per page.

        sort_by : typing.Optional[ApiActivitiesObjectInteractionsFilteredRequestSortBy]
            Sort key, '-'-prefixed for descending. Default is recency (-last_interaction_at); -interaction_count serves a most-visited view. Unknown values fall back to the default.

        start_time : typing.Optional[dt.datetime]
            Window start (ISO 8601). Overrides the summary_type/date window.

        summary_type : typing.Optional[str]
            Named window preset resolved relative to `date` (default: all).

        timezone_offset : typing.Optional[float]
            Hours of UTC-minus-local offset used to resolve day boundaries.

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Filter parameters keyed by field name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaginatedObjectInteractionList]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/activities/object-interactions/",
            method="POST",
            params={
                "date": str(date) if date is not None else None,
                "end_time": serialize_datetime(end_time) if end_time is not None else None,
                "feature_type": feature_type,
                "page": page,
                "page_size": page_size,
                "sort_by": sort_by,
                "start_time": serialize_datetime(start_time) if start_time is not None else None,
                "summary_type": summary_type,
                "timezone_offset": timezone_offset,
            },
            json={
                "filters": filters,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedObjectInteractionList,
                    parse_obj_as(
                        type_=PaginatedObjectInteractionList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
