# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.ch_thread_list import ChThreadList
from .raw_client import AsyncRawThreadsClient, RawThreadsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ThreadsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawThreadsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawThreadsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawThreadsClient
        """
        return self._raw_client

    def list_threads(
        self,
        *,
        id: str,
        thread_identifier: str,
        log_count: int,
        prompt_tokens: int,
        completion_tokens: int,
        tokens: int,
        cost: float,
        tokens_per_second: float,
        latency: float,
        time_to_first_token: float,
        thread_unique_id: typing.Optional[str] = OMIT,
        organization_name: typing.Optional[str] = OMIT,
        environment: typing.Optional[str] = OMIT,
        organization_id: typing.Optional[str] = OMIT,
        unique_organization_id: typing.Optional[str] = OMIT,
        organization_key_id: typing.Optional[str] = OMIT,
        created_at: typing.Optional[dt.datetime] = OMIT,
        updated_at: typing.Optional[dt.datetime] = OMIT,
        timestamp: typing.Optional[dt.datetime] = OMIT,
        input: typing.Optional[str] = OMIT,
        output: typing.Optional[str] = OMIT,
        storage_object_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ChThreadList:
        """
        Handle POST requests the same as GET for filtering.

        Parameters
        ----------
        id : str

        thread_identifier : str

        log_count : int

        prompt_tokens : int

        completion_tokens : int

        tokens : int

        cost : float

        tokens_per_second : float

        latency : float

        time_to_first_token : float

        thread_unique_id : typing.Optional[str]

        organization_name : typing.Optional[str]

        environment : typing.Optional[str]

        organization_id : typing.Optional[str]

        unique_organization_id : typing.Optional[str]

        organization_key_id : typing.Optional[str]

        created_at : typing.Optional[dt.datetime]

        updated_at : typing.Optional[dt.datetime]

        timestamp : typing.Optional[dt.datetime]

        input : typing.Optional[str]

        output : typing.Optional[str]

        storage_object_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChThreadList


        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.threads.list_threads(
            id="id",
            thread_identifier="thread_identifier",
            log_count=1,
            prompt_tokens=1,
            completion_tokens=1,
            tokens=1,
            cost=1.1,
            tokens_per_second=1.1,
            latency=1.1,
            time_to_first_token=1.1,
        )
        """
        _response = self._raw_client.list_threads(
            id=id,
            thread_identifier=thread_identifier,
            log_count=log_count,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            tokens=tokens,
            cost=cost,
            tokens_per_second=tokens_per_second,
            latency=latency,
            time_to_first_token=time_to_first_token,
            thread_unique_id=thread_unique_id,
            organization_name=organization_name,
            environment=environment,
            organization_id=organization_id,
            unique_organization_id=unique_organization_id,
            organization_key_id=organization_key_id,
            created_at=created_at,
            updated_at=updated_at,
            timestamp=timestamp,
            input=input,
            output=output,
            storage_object_key=storage_object_key,
            request_options=request_options,
        )
        return _response.data


class AsyncThreadsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawThreadsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawThreadsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawThreadsClient
        """
        return self._raw_client

    async def list_threads(
        self,
        *,
        id: str,
        thread_identifier: str,
        log_count: int,
        prompt_tokens: int,
        completion_tokens: int,
        tokens: int,
        cost: float,
        tokens_per_second: float,
        latency: float,
        time_to_first_token: float,
        thread_unique_id: typing.Optional[str] = OMIT,
        organization_name: typing.Optional[str] = OMIT,
        environment: typing.Optional[str] = OMIT,
        organization_id: typing.Optional[str] = OMIT,
        unique_organization_id: typing.Optional[str] = OMIT,
        organization_key_id: typing.Optional[str] = OMIT,
        created_at: typing.Optional[dt.datetime] = OMIT,
        updated_at: typing.Optional[dt.datetime] = OMIT,
        timestamp: typing.Optional[dt.datetime] = OMIT,
        input: typing.Optional[str] = OMIT,
        output: typing.Optional[str] = OMIT,
        storage_object_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ChThreadList:
        """
        Handle POST requests the same as GET for filtering.

        Parameters
        ----------
        id : str

        thread_identifier : str

        log_count : int

        prompt_tokens : int

        completion_tokens : int

        tokens : int

        cost : float

        tokens_per_second : float

        latency : float

        time_to_first_token : float

        thread_unique_id : typing.Optional[str]

        organization_name : typing.Optional[str]

        environment : typing.Optional[str]

        organization_id : typing.Optional[str]

        unique_organization_id : typing.Optional[str]

        organization_key_id : typing.Optional[str]

        created_at : typing.Optional[dt.datetime]

        updated_at : typing.Optional[dt.datetime]

        timestamp : typing.Optional[dt.datetime]

        input : typing.Optional[str]

        output : typing.Optional[str]

        storage_object_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChThreadList


        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.threads.list_threads(
                id="id",
                thread_identifier="thread_identifier",
                log_count=1,
                prompt_tokens=1,
                completion_tokens=1,
                tokens=1,
                cost=1.1,
                tokens_per_second=1.1,
                latency=1.1,
                time_to_first_token=1.1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_threads(
            id=id,
            thread_identifier=thread_identifier,
            log_count=log_count,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            tokens=tokens,
            cost=cost,
            tokens_per_second=tokens_per_second,
            latency=latency,
            time_to_first_token=time_to_first_token,
            thread_unique_id=thread_unique_id,
            organization_name=organization_name,
            environment=environment,
            organization_id=organization_id,
            unique_organization_id=unique_organization_id,
            organization_key_id=organization_key_id,
            created_at=created_at,
            updated_at=updated_at,
            timestamp=timestamp,
            input=input,
            output=output,
            storage_object_key=storage_object_key,
            request_options=request_options,
        )
        return _response.data
