# This file was auto-generated by Fern from our API Definition.

import typing

from .automation_condition_detail_condition_policy_value_value_zero_item import (
    AutomationConditionDetailConditionPolicyValueValueZeroItem,
)

AutomationConditionDetailConditionPolicyValueValue = typing.Union[
    typing.List[AutomationConditionDetailConditionPolicyValueValueZeroItem],
    str,
    int,
    float,
    bool,
    typing.List[str],
    typing.List[int],
    typing.List[float],
    typing.List[bool],
]
