# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .automation_condition_list_condition_policy_value import AutomationConditionListConditionPolicyValue


class AutomationConditionList(UniversalBaseModel):
    """
    Serializer for listing automation conditions with summarized information
    """

    id: typing.Optional[str] = None
    name: str = pydantic.Field()
    """
    Human-readable name for the condition
    """

    unique_organization_id: str = pydantic.Field()
    """
    Organization identifier
    """

    condition_policy: typing.Optional[typing.Dict[str, AutomationConditionListConditionPolicyValue]] = None
    time_step_minutes: typing.Optional[int] = pydantic.Field(default=None)
    """
    Time window in minutes for aggregation type conditions
    """

    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
