# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .behavior_catalog_entry_source import BehaviorCatalogEntrySource
from .behavior_catalog_entry_type import BehaviorCatalogEntryType
from .behavior_polarity import BehaviorPolarity


class BehaviorCatalogEntry(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Column ID, `behavior__<key>`. Spans list filters accept it as a filter key.
    """

    key: str = pydantic.Field()
    """
    Behavior key: a built-in behavior's name (for example `refusal`) or a custom behavior's `id`.
    """

    name: str = pydantic.Field()
    """
    Display name. For a built-in behavior, its key in title case (`Instruction Miss`). For a custom behavior, its `name`, else its `description`, else its `id`.
    """

    polarity: BehaviorPolarity
    type: BehaviorCatalogEntryType = pydantic.Field()
    """
    Always `boolean`.
    """

    source: BehaviorCatalogEntrySource = pydantic.Field()
    """
    `builtin` or `custom`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
