# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .behavior_span import BehaviorSpan


class BehaviorSpans(UniversalBaseModel):
    behavior: str = pydantic.Field()
    """
    Behavior key: a built-in behavior's name (for example `refusal`) or a custom behavior's `id`.
    """

    page: int
    page_size: int
    logs: typing.List[BehaviorSpan] = pydantic.Field()
    """
    Spans where the behavior fired, newest first. Fewer than `page_size` items means this is the last page. Empty when the behavior is turned off.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
