# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CachedOrganizationNotificationMethod(UniversalBaseModel):
    """
    Cached representation of an organization notification method.
    Used to avoid database hits during notification processing.
    """

    id: str
    unique_organization_id: str
    notification_type: str
    notification_config: typing.Dict[str, typing.Any]
    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
