# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .dashboard_llm_metrics_request_metrics_to_aggregate_item import DashboardLlmMetricsRequestMetricsToAggregateItem
from .dashboard_time_range_request import DashboardTimeRangeRequest


class DashboardLlmMetricsRequest(DashboardTimeRangeRequest):
    metrics_to_aggregate: typing.Optional[typing.List[DashboardLlmMetricsRequestMetricsToAggregateItem]] = (
        pydantic.Field(default=None)
    )
    """
    Optional. If provided, the response includes only these metric fields. If omitted, all LLM metrics are returned.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
