# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .error_incident_contributor_drilldown_filters import ErrorIncidentContributorDrilldownFilters


class ErrorIncidentContributor(UniversalBaseModel):
    fingerprint: str = pydantic.Field()
    """
    Error group fingerprint.
    """

    title: str
    error_class: str
    provider: str
    model: str = pydantic.Field()
    """
    Model of the group's latest failure.
    """

    endpoint: str
    status: int
    occurrence_count: int
    percentage: float = pydantic.Field()
    """
    Share of the incident's failures, 0 to 100.
    """

    affected_customers: int = pydantic.Field()
    """
    Distinct customers with a failure in this group.
    """

    first_seen_at: str = pydantic.Field()
    """
    First failure in the incident. UTC, ISO 8601 without a timezone suffix.
    """

    last_seen_at: str = pydantic.Field()
    """
    Latest failure in the incident. UTC, ISO 8601 without a timezone suffix.
    """

    error_group_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Path of Get an error group for this fingerprint.
    """

    drilldown_filters: ErrorIncidentContributorDrilldownFilters = pydantic.Field()
    """
    Time range and environment to pass to Get an error group to see the same failures.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
