# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .error_time_series_granularity import ErrorTimeSeriesGranularity
from .error_time_series_group_by import ErrorTimeSeriesGroupBy
from .error_time_series_point import ErrorTimeSeriesPoint


class ErrorTimeSeries(UniversalBaseModel):
    granularity: ErrorTimeSeriesGranularity
    group_by: ErrorTimeSeriesGroupBy
    series: typing.List[ErrorTimeSeriesPoint] = pydantic.Field()
    """
    Points ordered by `bucket`. Buckets with no failures are missing.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
