# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .evaluator_create_version_eval_class import EvaluatorCreateVersionEvalClass
from .type4e2enum import Type4E2Enum


class EvaluatorCreateVersion(UniversalBaseModel):
    """
    Serializer for creating a new version of an evaluator.
    Used for POST /evaluators/{evaluator_id}/versions/

    Supports two modes:
    1. Minimal payload (commit snapshot): Just provide version_description
       - All configuration fields are auto-copied from current draft
    2. Full payload (commit with changes): Provide full configuration
       - Client provides all fields, only identity fields are copied

    Signal handles: version increment, marking old versions as is_read_only=True

    Versioning model:
    - id: Evaluator identity (same across versions, copied from source)
    - version_id: Unique per row (auto-generated)
    - version: Version number (0, 1, 2...) - set by signal
    - is_read_only: False for new version (draft), True for old versions
    - version_description: Commit message for this version
    """

    version_id: typing.Optional[str] = None
    configurations: typing.Optional[typing.Dict[str, typing.Any]] = None
    categorical_choices: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = None
    score_config: typing.Optional[typing.Dict[str, typing.Any]] = None
    passing_conditions: typing.Optional[typing.Dict[str, typing.Any]] = None
    llm_config: typing.Optional[typing.Dict[str, typing.Any]] = None
    code_config: typing.Optional[typing.Dict[str, typing.Any]] = None
    project: typing.Optional[str] = None
    is_public: typing.Optional[bool] = None
    id: typing.Optional[str] = None
    version: typing.Optional[int] = None
    is_read_only: typing.Optional[bool] = None
    name: typing.Optional[str] = None
    score_value_type: typing.Optional[str] = None
    version_description: typing.Optional[str] = None
    description: typing.Optional[str] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    type: typing.Optional[Type4E2Enum] = None
    eval_class: typing.Optional[EvaluatorCreateVersionEvalClass] = None
    custom_required_fields: typing.Optional[typing.List[str]] = None
    starred: typing.Optional[bool] = None
    created_by: typing.Optional[int] = None
    updated_by: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
