# This file was auto-generated by Fern from our API Definition.

import typing

FilterValueOperator = typing.Union[
    typing.Literal[
        "", "iexact", "lt", "lte", "gt", "gte", "contains", "icontains", "startswith", "endswith", "in", "isnull", "not"
    ],
    typing.Any,
]
