# This file was auto-generated by Fern from our API Definition.

import typing

FilterOperatorEnum = typing.Union[
    typing.Literal[
        "=",
        "eq",
        "equals",
        "in",
        "not",
        "contains",
        "icontains",
        "startswith",
        "endswith",
        "gt",
        "gte",
        "lt",
        "lte",
        "isnull",
        "regex",
        "ilike",
        "trigram_word_similar",
        "full_text_search",
        "empty",
        "notEmpty",
        "not_empty",
    ],
    typing.Any,
]
