# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ModelStatusBucket(UniversalBaseModel):
    """
    One time bucket of an uptime series; the bucket size is `time_tick`
    (minute / hour / day).
    """

    date_group: dt.datetime = pydantic.Field()
    """
    Start of the time bucket (UTC). One bucket per `time_tick` step.
    """

    uptime: typing.Optional[float] = pydantic.Field(default=None)
    """
    Uptime fraction for the bucket in [0, 1]; `null` when the bucket had no traffic. For the per-provider `data` series this is `(requests - down) / requests`; for `respan_uptime` it is `up_requests / (up_requests + down_requests)` (user-error-only requests excluded).
    """

    total_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Admin-only. Denominator request count for the bucket. Omitted for public callers (volume is revenue-inferable).
    """

    down_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Admin-only. Requests counted as down (HTTP 5xx or 408 timeout) in the bucket. Omitted for public callers.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
