# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ModelStatusResponseStatus(UniversalBaseModel):
    """
    Omitted when provider_id is supplied. Volume fields are staff-only.
    """

    uptime_percent: typing.Optional[float] = None
    average_tps: typing.Optional[float] = None
    average_ttft: typing.Optional[float] = None
    average_latency: typing.Optional[float] = None
    cache_hit_percentage: typing.Optional[float] = None
    input_cost: typing.Optional[float] = None
    number_of_requests: typing.Optional[int] = None
    cost: typing.Optional[float] = None
    prompt_tokens: typing.Optional[int] = None
    completion_tokens: typing.Optional[int] = None
    prompt_cache_hit_tokens: typing.Optional[int] = None
    prompt_cache_creation_tokens: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
