# This file was auto-generated by Fern from our API Definition.

import typing

from .blank_enum import BlankEnum
from .provider_name_enum import ProviderNameEnum

PatchedTechnicalPartnershipIntegrationRequestProviderName = typing.Union[ProviderNameEnum, BlankEnum]
