# This file was auto-generated by Fern from our API Definition.

import typing

PlanEnum = typing.Union[
    typing.Literal[
        "none",
        "starter",
        "team",
        "custom",
        "seat_based_free",
        "seat_based_pro",
        "seat_based_team",
        "seat_based_enterprise",
        "seat_based_custom",
        "respan_team",
        "respan_pro",
    ],
    typing.Any,
]
