# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PointsTransactionDetail(UniversalBaseModel):
    """
    Detail view of points transactions (full row) — reads ``ch_billing_event``.
    """

    id: typing.Optional[str] = None
    unique_organization_id: typing.Optional[str] = None
    points_amount: typing.Optional[float] = None
    event_class: typing.Optional[str] = None
    event_time: typing.Optional[dt.datetime] = None
    description: typing.Optional[str] = None
    source_id: typing.Optional[str] = None
    credit_amount: typing.Optional[float] = None
    debit_amount: typing.Optional[float] = None
    points_conversion_rate: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
