# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PublicTestsetSheetDetail(UniversalBaseModel):
    """
    Detail serializer for testsets with masked fields for API key users
    """

    testset_unique_id: typing.Optional[str] = None
    project: typing.Optional[str] = None
    id: typing.Optional[str] = None
    created_at: typing.Optional[dt.datetime] = None
    name: str
    description: typing.Optional[str] = None
    updated_at: typing.Optional[dt.datetime] = None
    row_count: typing.Optional[int] = None
    column_count: typing.Optional[int] = None
    max_insertions_before_rebalance: typing.Optional[int] = None
    used_row_indexes: typing.Optional[typing.List[float]] = None
    current_max_row_index: typing.Optional[float] = None
    column_definitions: typing.Optional[typing.List[typing.Any]] = None
    starred: typing.Optional[bool] = None
    created_by: typing.Optional[int] = None
    organization: typing.Optional[int] = None
    updated_by: typing.Optional[int] = None
    tags: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
