# This file was auto-generated by Fern from our API Definition.

import typing

from .blank_enum import BlankEnum
from .environment_a4f_enum import EnvironmentA4FEnum
from .null_enum import NullEnum

SavedFilterCreateEnvironment = typing.Union[EnvironmentA4FEnum, BlankEnum, typing.Optional[NullEnum]]
