# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .type_safe_saved_credentials_respan_params_credential_override_value import (
    TypeSafeSavedCredentialsRespanParamsCredentialOverrideValue,
)


class TypeSafeSavedCredentialsRespanParams(UniversalBaseModel):
    """
    **TypeSafe API key required unless already saved in Settings > Providers.** Enter it below in credential_override → jev-1.13.0 → api_key. Respan removes these parameters before forwarding the request.
    """

    credential_override: typing.Optional[
        typing.Dict[str, TypeSafeSavedCredentialsRespanParamsCredentialOverrideValue]
    ] = pydantic.Field(default=None)
    """
    **Required unless a TypeSafe key is saved in Settings > Providers.** Keep the selector jev-1.13.0 and replace YOUR_TYPESAFE_API_KEY with your TypeSafe provider key.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
