# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WorkflowExportWorkflow(UniversalBaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    trigger_event_type: typing.Optional[str] = None
    schedule_cron: typing.Optional[str] = None
    is_enabled: typing.Optional[bool] = None
    tasks: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
