# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs


class WorkflowFilterRequestRequest(UniversalBaseModel):
    """
    Request body for POST-for-filtering on /api/workflows/list/.
    """

    filters: typing.Optional["FilterParamDictPydantic"] = pydantic.Field(default=None)
    """
    Filter parameters keyed by field name.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .filter_bundle_pydantic import FilterBundlePydantic  # noqa: E402, I001
from .filter_param_dict_pydantic import FilterParamDictPydantic  # noqa: E402, I001
from .filter_param_dict_pydantic_value import FilterParamDictPydanticValue  # noqa: E402, I001

update_forward_refs(
    WorkflowFilterRequestRequest,
    FilterBundlePydantic=FilterBundlePydantic,
    FilterParamDictPydantic=FilterParamDictPydantic,
    FilterParamDictPydanticValue=FilterParamDictPydanticValue,
)
