# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .workflow_create_tasks_item import WorkflowCreateTasksItem
from .workflow_create_trigger_event_type import WorkflowCreateTriggerEventType
from .workflow_version_type_enum import WorkflowVersionTypeEnum


class WorkflowCreate(UniversalBaseModel):
    """
    Validate workflow task structure on create/update via validate_workflow_structure().
    """

    id: typing.Optional[str] = None
    unique_organization_id: typing.Optional[str] = None
    tasks: typing.Optional[typing.List[WorkflowCreateTasksItem]] = None
    project: typing.Optional[str] = None
    workflow_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Logical workflow family key shared across versions
    """

    version: typing.Optional[int] = None
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    type: typing.Optional[WorkflowVersionTypeEnum] = pydantic.Field(default=None)
    """
    Kind of workflow: automation, monitor, or evaluator
    
    * `automations` - Automation
    * `monitors` - Monitor
    * `evaluators` - Evaluator
    * `reports` - Report
    * `exports` - Export
    * `ingests` - Ingest
    """

    trigger_event_type: typing.Optional[WorkflowCreateTriggerEventType] = pydantic.Field(default=None)
    """
    Event type that triggers this workflow when used as an event responder
    
    * `request_log` - LOG_INGESTED
    * `trace_completed` - TRACE_COMPLETED
    * `customer_budget_limit_reached` - BUDGET_EXCEEDED
    * `credit_low_balance_threshold_reached` - CREDIT_LOW
    * `spend_cap_warning_threshold_reached` - SPEND_CAP_WARNING
    * `limit_policy_soft_triggered` - LIMIT_POLICY_SOFT_TRIGGERED
    * `limit_policy_hard_triggered` - LIMIT_POLICY_HARD_TRIGGERED
    * `on_eval_result_ingested` - EVAL_COMPLETED
    * `custom_event` - CUSTOM_EVENT
    * `eval_only` - EVAL_ONLY
    * `scheduled` - SCHEDULED
    """

    schedule_cron: typing.Optional[str] = pydantic.Field(default=None)
    """
    UTC cron schedule (5-field). Populated when trigger_event_type='scheduled'.
    """

    has_async_steps: typing.Optional[bool] = None
    is_enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Only committed (is_read_only=True) versions may be enabled. At most one version per workflow family should be enabled at a time.
    """

    is_starred: typing.Optional[bool] = None
    is_read_only: typing.Optional[bool] = pydantic.Field(default=None)
    """
    True for committed versions; only the latest version is editable
    """

    resource_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    All resource IDs referenced in workflow (for reverse lookup)
    """

    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    organization: typing.Optional[int] = None
    updated_by: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(WorkflowCreate)
