# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .update_evaluator_response_categorical_choices_item import UpdateEvaluatorResponseCategoricalChoicesItem
from .update_evaluator_response_configurations import UpdateEvaluatorResponseConfigurations
from .update_evaluator_response_created_by import UpdateEvaluatorResponseCreatedBy
from .update_evaluator_response_updated_by import UpdateEvaluatorResponseUpdatedBy


class UpdateEvaluatorResponse(UniversalBaseModel):
    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    evaluator_slug: typing.Optional[str] = None
    type: typing.Optional[str] = None
    score_value_type: typing.Optional[str] = None
    eval_class: typing.Optional[str] = None
    description: typing.Optional[str] = None
    configurations: typing.Optional[UpdateEvaluatorResponseConfigurations] = None
    created_by: typing.Optional[UpdateEvaluatorResponseCreatedBy] = None
    updated_by: typing.Optional[UpdateEvaluatorResponseUpdatedBy] = None
    created_at: typing.Optional[str] = None
    updated_at: typing.Optional[str] = None
    custom_required_fields: typing.Optional[typing.List[str]] = None
    categorical_choices: typing.Optional[typing.List[UpdateEvaluatorResponseCategoricalChoicesItem]] = None
    starred: typing.Optional[bool] = None
    organization: typing.Optional[int] = None
    tags: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
