# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .retrieve_credit_transaction_response_transaction_type import RetrieveCreditTransactionResponseTransactionType


class RetrieveCreditTransactionResponse(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Transaction ID.
    """

    organization_subscription: typing.Optional[int] = pydantic.Field(default=None)
    """
    Organization subscription ID.
    """

    unique_organization_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Organization UUID.
    """

    amount: typing.Optional[float] = pydantic.Field(default=None)
    """
    Transaction amount in USD. Negative for deductions.
    """

    transaction_type: typing.Optional[RetrieveCreditTransactionResponseTransactionType] = pydantic.Field(default=None)
    """
    Transaction type.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Transaction timestamp.
    """

    expires_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Expiration date for time-limited credits.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Transaction description.
    """

    stripe_payment_intent_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stripe payment intent ID (for purchases).
    """

    metadata: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Custom metadata.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
