# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_chat_completion_response_content_item import CreateChatCompletionResponseContentItem


class CreateChatCompletionResponse(UniversalBaseModel):
    role: typing.Optional[str] = None
    content: typing.Optional[typing.List[CreateChatCompletionResponseContentItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
