# This file was auto-generated by Fern from our API Definition.

import typing

CreateChatCompletionRequestMessagesItemRole = typing.Union[
    typing.Literal["system", "user", "assistant", "tool"], typing.Any
]
