# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .dashboard_breakdown_request_breakdown_by import DashboardBreakdownRequestBreakdownBy
    from .dashboard_breakdown_request_metrics_to_aggregate_item import DashboardBreakdownRequestMetricsToAggregateItem
    from .get_platform_stats_request_breakdown_by import GetPlatformStatsRequestBreakdownBy
    from .get_storage_volume_summary_request_time_tick import GetStorageVolumeSummaryRequestTimeTick
    from .list_storage_volume_request_time_tick import ListStorageVolumeRequestTimeTick
    from .list_top_api_keys_request_sort_by import ListTopApiKeysRequestSortBy
    from .list_top_api_keys_request_summary_type import ListTopApiKeysRequestSummaryType
    from .list_top_deployments_request_sort_by import ListTopDeploymentsRequestSortBy
    from .list_top_deployments_request_summary_type import ListTopDeploymentsRequestSummaryType
    from .list_top_models_request_sort_by import ListTopModelsRequestSortBy
    from .list_top_models_request_summary_type import ListTopModelsRequestSummaryType
    from .list_top_prompts_request_sort_by import ListTopPromptsRequestSortBy
    from .list_top_prompts_request_summary_type import ListTopPromptsRequestSummaryType
    from .list_top_providers_request_sort_by import ListTopProvidersRequestSortBy
    from .list_top_providers_request_summary_type import ListTopProvidersRequestSummaryType
    from .list_top_users_request_sort_by import ListTopUsersRequestSortBy
    from .list_top_users_request_summary_type import ListTopUsersRequestSummaryType
_dynamic_imports: typing.Dict[str, str] = {
    "DashboardBreakdownRequestBreakdownBy": ".dashboard_breakdown_request_breakdown_by",
    "DashboardBreakdownRequestMetricsToAggregateItem": ".dashboard_breakdown_request_metrics_to_aggregate_item",
    "GetPlatformStatsRequestBreakdownBy": ".get_platform_stats_request_breakdown_by",
    "GetStorageVolumeSummaryRequestTimeTick": ".get_storage_volume_summary_request_time_tick",
    "ListStorageVolumeRequestTimeTick": ".list_storage_volume_request_time_tick",
    "ListTopApiKeysRequestSortBy": ".list_top_api_keys_request_sort_by",
    "ListTopApiKeysRequestSummaryType": ".list_top_api_keys_request_summary_type",
    "ListTopDeploymentsRequestSortBy": ".list_top_deployments_request_sort_by",
    "ListTopDeploymentsRequestSummaryType": ".list_top_deployments_request_summary_type",
    "ListTopModelsRequestSortBy": ".list_top_models_request_sort_by",
    "ListTopModelsRequestSummaryType": ".list_top_models_request_summary_type",
    "ListTopPromptsRequestSortBy": ".list_top_prompts_request_sort_by",
    "ListTopPromptsRequestSummaryType": ".list_top_prompts_request_summary_type",
    "ListTopProvidersRequestSortBy": ".list_top_providers_request_sort_by",
    "ListTopProvidersRequestSummaryType": ".list_top_providers_request_summary_type",
    "ListTopUsersRequestSortBy": ".list_top_users_request_sort_by",
    "ListTopUsersRequestSummaryType": ".list_top_users_request_summary_type",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "DashboardBreakdownRequestBreakdownBy",
    "DashboardBreakdownRequestMetricsToAggregateItem",
    "GetPlatformStatsRequestBreakdownBy",
    "GetStorageVolumeSummaryRequestTimeTick",
    "ListStorageVolumeRequestTimeTick",
    "ListTopApiKeysRequestSortBy",
    "ListTopApiKeysRequestSummaryType",
    "ListTopDeploymentsRequestSortBy",
    "ListTopDeploymentsRequestSummaryType",
    "ListTopModelsRequestSortBy",
    "ListTopModelsRequestSummaryType",
    "ListTopPromptsRequestSortBy",
    "ListTopPromptsRequestSummaryType",
    "ListTopProvidersRequestSortBy",
    "ListTopProvidersRequestSummaryType",
    "ListTopUsersRequestSortBy",
    "ListTopUsersRequestSummaryType",
]
