# This file was auto-generated by Fern from our API Definition.

import typing

CreateTraceLegacyRequestBodyZeroItemLogType = typing.Union[
    typing.Literal[
        "chat",
        "completion",
        "response",
        "embedding",
        "speech",
        "transcription",
        "workflow",
        "agent",
        "task",
        "tool",
        "guardrail",
        "reranker",
        "other",
    ],
    typing.Any,
]
