# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class RetrieveTraceResponseSpanTreeItem(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Span identifier.
    """

    unique_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Underlying log unique ID.
    """

    span_unique_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique span identifier within the trace.
    """

    span_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Span name.
    """

    span_parent_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Parent span ID.
    """

    trace_unique_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Trace ID.
    """

    customer_identifier: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer identifier.
    """

    thread_identifier: typing.Optional[str] = pydantic.Field(default=None)
    """
    Thread identifier when present.
    """

    session_identifier: typing.Optional[str] = pydantic.Field(default=None)
    """
    Session identifier when present.
    """

    organization_key_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    API key identifier.
    """

    organization_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Organization unique ID.
    """

    environment: typing.Optional[str] = pydantic.Field(default=None)
    """
    Environment.
    """

    log_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Span/log type.
    """

    timestamp: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Span end time.
    """

    start_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Span start time.
    """

    end_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Alias of `timestamp`.
    """

    prompt_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Prompt tokens for this span.
    """

    completion_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Completion tokens for this span.
    """

    total_request_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total tokens for this span.
    """

    cost: typing.Optional[float] = pydantic.Field(default=None)
    """
    Span cost in USD.
    """

    model: typing.Optional[str] = pydantic.Field(default=None)
    """
    Model used by the span.
    """

    latency: typing.Optional[float] = pydantic.Field(default=None)
    """
    Span duration in seconds.
    """

    status_code: typing.Optional[int] = pydantic.Field(default=None)
    """
    Status code recorded for the span.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Span status.
    """

    input: typing.Optional[str] = pydantic.Field(default=None)
    """
    Span input.
    """

    output: typing.Optional[str] = pydantic.Field(default=None)
    """
    Span output.
    """

    metadata: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Span metadata.
    """

    span_links: typing.Optional[str] = pydantic.Field(default=None)
    """
    Serialized OTEL span links when present.
    """

    storage_object_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    Backing storage object key when present.
    """

    span_workflow_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Workflow name when present.
    """

    children: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    """
    Nested child spans.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
