# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawAutomationsClient, RawAutomationsClient
from .types.create_automation_request_automation_type import CreateAutomationRequestAutomationType
from .types.create_automation_request_configuration import CreateAutomationRequestConfiguration
from .types.create_automation_response import CreateAutomationResponse
from .types.create_condition_request_condition_policy import CreateConditionRequestConditionPolicy
from .types.create_condition_request_condition_type import CreateConditionRequestConditionType
from .types.create_condition_response import CreateConditionResponse
from .types.list_conditions_response import ListConditionsResponse
from .types.update_automation_request_configuration import UpdateAutomationRequestConfiguration
from .types.update_automation_response import UpdateAutomationResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AutomationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAutomationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAutomationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAutomationsClient
        """
        return self._raw_client

    def list_conditions(
        self,
        *,
        authorization: str,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        condition_type: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListConditionsResponse:
        """
        List automation conditions with pagination and filtering.

        Parameters
        ----------
        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        page : typing.Optional[int]
            Page number.

        page_size : typing.Optional[int]
            Results per page.

        search : typing.Optional[str]
            Search conditions by name or slug.

        condition_type : typing.Optional[str]
            Filter by condition type.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListConditionsResponse
            Paginated list of conditions.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient()
        client.automations.list_conditions(
            authorization="Bearer sk_live_xxxxx",
            condition_type="single_log",
        )
        """
        _response = self._raw_client.list_conditions(
            authorization=authorization,
            page=page,
            page_size=page_size,
            search=search,
            condition_type=condition_type,
            request_options=request_options,
        )
        return _response.data

    def create_condition(
        self,
        *,
        authorization: str,
        name: str,
        condition_slug: str,
        condition_type: CreateConditionRequestConditionType,
        condition_policy: CreateConditionRequestConditionPolicy,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateConditionResponse:
        """
        Create an automation condition that defines which spans should trigger evaluations.

        Parameters
        ----------
        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        name : str
            Display name.

        condition_slug : str
            Unique identifier.

        condition_type : CreateConditionRequestConditionType
            Condition type.

        condition_policy : CreateConditionRequestConditionPolicy
            Policy defining evaluation rules.

        description : typing.Optional[str]
            Condition description.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateConditionResponse
            Successful response for Create condition

        Examples
        --------
        from respan import RespanClient
        from respan.automations import (
            CreateConditionRequestConditionPolicy,
            CreateConditionRequestConditionPolicyRulesItem,
        )

        client = RespanClient()
        client.automations.create_condition(
            authorization="Bearer sk_live_xxxxx",
            name="Successful Requests",
            condition_slug="success_logs",
            condition_type="single_log",
            condition_policy=CreateConditionRequestConditionPolicy(
                rules=[
                    CreateConditionRequestConditionPolicyRulesItem(
                        field="status_code",
                        operator="equals",
                        value=200,
                    )
                ],
                connector="AND",
            ),
        )
        """
        _response = self._raw_client.create_condition(
            authorization=authorization,
            name=name,
            condition_slug=condition_slug,
            condition_type=condition_type,
            condition_policy=condition_policy,
            description=description,
            request_options=request_options,
        )
        return _response.data

    def create_automation(
        self,
        *,
        authorization: str,
        automation_slug: str,
        name: str,
        automation_type: CreateAutomationRequestAutomationType,
        condition: str,
        evaluator_ids: typing.Sequence[str],
        configuration: CreateAutomationRequestConfiguration,
        is_enabled: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateAutomationResponse:
        """
        Create an online evaluation automation that automatically runs evaluators on spans matching specified conditions.

        Parameters
        ----------
        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        automation_slug : str
            Unique identifier.

        name : str
            Human-readable name.

        automation_type : CreateAutomationRequestAutomationType
            Automation type.

        condition : str
            Condition ID (from Create Condition endpoint).

        evaluator_ids : typing.Sequence[str]
            Evaluator UUIDs to run (from List Evaluators).

        configuration : CreateAutomationRequestConfiguration
            Automation configuration.

        is_enabled : typing.Optional[bool]
            Whether automation is active.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAutomationResponse
            Successful response for Create automation

        Examples
        --------
        from respan import RespanClient
        from respan.automations import CreateAutomationRequestConfiguration

        client = RespanClient()
        client.automations.create_automation(
            authorization="Bearer sk_live_xxxxx",
            automation_slug="prod_quality_monitor",
            name="Production Quality Monitor",
            automation_type="online_eval",
            condition="cond-12345",
            evaluator_ids=["eval-quality-uuid", "eval-safety-uuid"],
            configuration=CreateAutomationRequestConfiguration(),
        )
        """
        _response = self._raw_client.create_automation(
            authorization=authorization,
            automation_slug=automation_slug,
            name=name,
            automation_type=automation_type,
            condition=condition,
            evaluator_ids=evaluator_ids,
            configuration=configuration,
            is_enabled=is_enabled,
            request_options=request_options,
        )
        return _response.data

    def update_automation(
        self,
        automation_id: str,
        *,
        authorization: str,
        is_enabled: typing.Optional[bool] = OMIT,
        configuration: typing.Optional[UpdateAutomationRequestConfiguration] = OMIT,
        evaluator_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateAutomationResponse:
        """
        Update an automation. Use to enable/disable, change sampling rate, or update evaluator list. Only provided fields are updated.

        Parameters
        ----------
        automation_id : str
            Automation Id

        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        is_enabled : typing.Optional[bool]
            Enable or disable the automation.

        configuration : typing.Optional[UpdateAutomationRequestConfiguration]

        evaluator_ids : typing.Optional[typing.Sequence[str]]
            Updated evaluator UUIDs.

        name : typing.Optional[str]
            Automation name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateAutomationResponse
            Successful response for Update automation

        Examples
        --------
        from respan import RespanClient

        client = RespanClient()
        client.automations.update_automation(
            automation_id="automation_id",
            authorization="Bearer sk_live_xxxxx",
        )
        """
        _response = self._raw_client.update_automation(
            automation_id,
            authorization=authorization,
            is_enabled=is_enabled,
            configuration=configuration,
            evaluator_ids=evaluator_ids,
            name=name,
            request_options=request_options,
        )
        return _response.data


class AsyncAutomationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAutomationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAutomationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAutomationsClient
        """
        return self._raw_client

    async def list_conditions(
        self,
        *,
        authorization: str,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        condition_type: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListConditionsResponse:
        """
        List automation conditions with pagination and filtering.

        Parameters
        ----------
        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        page : typing.Optional[int]
            Page number.

        page_size : typing.Optional[int]
            Results per page.

        search : typing.Optional[str]
            Search conditions by name or slug.

        condition_type : typing.Optional[str]
            Filter by condition type.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListConditionsResponse
            Paginated list of conditions.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient()


        async def main() -> None:
            await client.automations.list_conditions(
                authorization="Bearer sk_live_xxxxx",
                condition_type="single_log",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_conditions(
            authorization=authorization,
            page=page,
            page_size=page_size,
            search=search,
            condition_type=condition_type,
            request_options=request_options,
        )
        return _response.data

    async def create_condition(
        self,
        *,
        authorization: str,
        name: str,
        condition_slug: str,
        condition_type: CreateConditionRequestConditionType,
        condition_policy: CreateConditionRequestConditionPolicy,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateConditionResponse:
        """
        Create an automation condition that defines which spans should trigger evaluations.

        Parameters
        ----------
        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        name : str
            Display name.

        condition_slug : str
            Unique identifier.

        condition_type : CreateConditionRequestConditionType
            Condition type.

        condition_policy : CreateConditionRequestConditionPolicy
            Policy defining evaluation rules.

        description : typing.Optional[str]
            Condition description.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateConditionResponse
            Successful response for Create condition

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient
        from respan.automations import (
            CreateConditionRequestConditionPolicy,
            CreateConditionRequestConditionPolicyRulesItem,
        )

        client = AsyncRespanClient()


        async def main() -> None:
            await client.automations.create_condition(
                authorization="Bearer sk_live_xxxxx",
                name="Successful Requests",
                condition_slug="success_logs",
                condition_type="single_log",
                condition_policy=CreateConditionRequestConditionPolicy(
                    rules=[
                        CreateConditionRequestConditionPolicyRulesItem(
                            field="status_code",
                            operator="equals",
                            value=200,
                        )
                    ],
                    connector="AND",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_condition(
            authorization=authorization,
            name=name,
            condition_slug=condition_slug,
            condition_type=condition_type,
            condition_policy=condition_policy,
            description=description,
            request_options=request_options,
        )
        return _response.data

    async def create_automation(
        self,
        *,
        authorization: str,
        automation_slug: str,
        name: str,
        automation_type: CreateAutomationRequestAutomationType,
        condition: str,
        evaluator_ids: typing.Sequence[str],
        configuration: CreateAutomationRequestConfiguration,
        is_enabled: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateAutomationResponse:
        """
        Create an online evaluation automation that automatically runs evaluators on spans matching specified conditions.

        Parameters
        ----------
        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        automation_slug : str
            Unique identifier.

        name : str
            Human-readable name.

        automation_type : CreateAutomationRequestAutomationType
            Automation type.

        condition : str
            Condition ID (from Create Condition endpoint).

        evaluator_ids : typing.Sequence[str]
            Evaluator UUIDs to run (from List Evaluators).

        configuration : CreateAutomationRequestConfiguration
            Automation configuration.

        is_enabled : typing.Optional[bool]
            Whether automation is active.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAutomationResponse
            Successful response for Create automation

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient
        from respan.automations import CreateAutomationRequestConfiguration

        client = AsyncRespanClient()


        async def main() -> None:
            await client.automations.create_automation(
                authorization="Bearer sk_live_xxxxx",
                automation_slug="prod_quality_monitor",
                name="Production Quality Monitor",
                automation_type="online_eval",
                condition="cond-12345",
                evaluator_ids=["eval-quality-uuid", "eval-safety-uuid"],
                configuration=CreateAutomationRequestConfiguration(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_automation(
            authorization=authorization,
            automation_slug=automation_slug,
            name=name,
            automation_type=automation_type,
            condition=condition,
            evaluator_ids=evaluator_ids,
            configuration=configuration,
            is_enabled=is_enabled,
            request_options=request_options,
        )
        return _response.data

    async def update_automation(
        self,
        automation_id: str,
        *,
        authorization: str,
        is_enabled: typing.Optional[bool] = OMIT,
        configuration: typing.Optional[UpdateAutomationRequestConfiguration] = OMIT,
        evaluator_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateAutomationResponse:
        """
        Update an automation. Use to enable/disable, change sampling rate, or update evaluator list. Only provided fields are updated.

        Parameters
        ----------
        automation_id : str
            Automation Id

        authorization : str
            Bearer token. Use `Bearer YOUR_API_KEY`.

        is_enabled : typing.Optional[bool]
            Enable or disable the automation.

        configuration : typing.Optional[UpdateAutomationRequestConfiguration]

        evaluator_ids : typing.Optional[typing.Sequence[str]]
            Updated evaluator UUIDs.

        name : typing.Optional[str]
            Automation name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateAutomationResponse
            Successful response for Update automation

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient()


        async def main() -> None:
            await client.automations.update_automation(
                automation_id="automation_id",
                authorization="Bearer sk_live_xxxxx",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_automation(
            automation_id,
            authorization=authorization,
            is_enabled=is_enabled,
            configuration=configuration,
            evaluator_ids=evaluator_ids,
            name=name,
            request_options=request_options,
        )
        return _response.data
