# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.automation_condition_create import AutomationConditionCreate
from ..types.automation_condition_detail import AutomationConditionDetail
from ..types.automation_condition_list import AutomationConditionList
from ..types.automation_condition_update import AutomationConditionUpdate
from ..types.paginated_automation_condition_list_list import PaginatedAutomationConditionListList
from .raw_client import AsyncRawAutomationsClient, RawAutomationsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AutomationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAutomationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAutomationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAutomationsClient
        """
        return self._raw_client

    def conditions_list(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedAutomationConditionListList:
        """
        REST API view for listing and creating automation conditions.

        This view handles:
        - GET: List automation conditions with filtering and pagination
        - POST: Create new automation conditions or filter existing ones

        Superadmin: Can LIST all conditions across all organizations.
        Regular users: Can only access conditions in their organization.

        Authentication: JWT token or API Key
        Permissions: Automatic via JWTAndAPIKeyAuthenticationViewMixin
        Pagination: LogPaginator

        Parameters
        ----------
        page : typing.Optional[int]
            A page number within the paginated result set.

        page_size : typing.Optional[int]
            Number of results to return per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedAutomationConditionListList


        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.automations.conditions_list()
        """
        _response = self._raw_client.conditions_list(page=page, page_size=page_size, request_options=request_options)
        return _response.data

    def conditions_create(
        self,
        *,
        name: str,
        condition_policy: typing.Any,
        id: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        filter_set_id: typing.Optional[str] = OMIT,
        time_step_minutes: typing.Optional[int] = OMIT,
        sampling_rate: typing.Optional[float] = OMIT,
        updated_by: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AutomationConditionCreate:
        """
        Handle POST requests for both creation and filtering.

        Determines whether the request is for creating a new condition
        or filtering existing conditions based on the presence of
        creation-specific fields.

        Args:
            request: HTTP request object

        Returns:
            Response: Either creation response or filtered list response

        Parameters
        ----------
        name : str
            Human-readable name for the condition

        condition_policy : typing.Any

        id : typing.Optional[str]

        description : typing.Optional[str]
            Description of what this condition does

        filter_set_id : typing.Optional[str]
            Filter set identifier for log filtering

        time_step_minutes : typing.Optional[int]
            Time window in minutes for aggregation type conditions

        sampling_rate : typing.Optional[float]
            Sampling rate for single log conditions (0.0 to 1.0)

        updated_by : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AutomationConditionCreate


        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.automations.conditions_create(
            name="x",
            condition_policy={"key": "value"},
        )
        """
        _response = self._raw_client.conditions_create(
            name=name,
            condition_policy=condition_policy,
            id=id,
            description=description,
            filter_set_id=filter_set_id,
            time_step_minutes=time_step_minutes,
            sampling_rate=sampling_rate,
            updated_by=updated_by,
            request_options=request_options,
        )
        return _response.data

    def conditions_update(
        self,
        *,
        name: str,
        unique_organization_id: str,
        time_step_minutes: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AutomationConditionList:
        """
        PUT handler with superadmin lock and field protection.

        Same as patch() - checks lock and field protection before delegating.

        Parameters
        ----------
        name : str
            Human-readable name for the condition

        unique_organization_id : str
            Organization identifier

        time_step_minutes : typing.Optional[int]
            Time window in minutes for aggregation type conditions

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AutomationConditionList


        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.automations.conditions_update(
            name="name",
            unique_organization_id="unique_organization_id",
        )
        """
        _response = self._raw_client.conditions_update(
            name=name,
            unique_organization_id=unique_organization_id,
            time_step_minutes=time_step_minutes,
            request_options=request_options,
        )
        return _response.data

    def conditions_partial_update(
        self,
        *,
        name: typing.Optional[str] = OMIT,
        unique_organization_id: typing.Optional[str] = OMIT,
        time_step_minutes: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AutomationConditionList:
        """
        PATCH handler with superadmin lock and field protection.

        Checks:
        1. Object lock (is_managed=True -> non-superadmins can't modify)
        2. Field protection (non-superadmins can't modify specific fields)

        Parameters
        ----------
        name : typing.Optional[str]
            Human-readable name for the condition

        unique_organization_id : typing.Optional[str]
            Organization identifier

        time_step_minutes : typing.Optional[int]
            Time window in minutes for aggregation type conditions

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AutomationConditionList


        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.automations.conditions_partial_update()
        """
        _response = self._raw_client.conditions_partial_update(
            name=name,
            unique_organization_id=unique_organization_id,
            time_step_minutes=time_step_minutes,
            request_options=request_options,
        )
        return _response.data

    def conditions_retrieve(
        self, condition_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AutomationConditionDetail:
        """
        REST API view for retrieving, updating, and deleting individual automation conditions.

        This view handles:
        - GET: Retrieve a specific automation condition by condition_id
        - PUT/PATCH: Update an existing automation condition
        - DELETE: Delete an automation condition

        Superadmin: Can access any condition across all organizations.
        Regular users: Can only access conditions in their organization.

        Lookup field: id (condition_id in URL)
        Authentication: JWT token or API Key
        Permissions: Automatic via JWTAndAPIKeyAuthenticationViewMixin

        Parameters
        ----------
        condition_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AutomationConditionDetail


        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.automations.conditions_retrieve(
            condition_id="condition_id",
        )
        """
        _response = self._raw_client.conditions_retrieve(condition_id, request_options=request_options)
        return _response.data

    def conditions_create2(
        self,
        condition_id: str,
        *,
        name: str,
        unique_organization_id: str,
        description: typing.Optional[str] = OMIT,
        filter_set_id: typing.Optional[str] = OMIT,
        sampling_rate: typing.Optional[float] = OMIT,
        time_step_minutes: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AutomationConditionDetail:
        """
        POST handler with superadmin-only field protection.

        Strips superadmin-only fields from non-superadmin requests before
        delegating to OrganizationInjectionMixin.post() for org injection.

        Parameters
        ----------
        condition_id : str

        name : str
            Human-readable name for the condition

        unique_organization_id : str
            Organization identifier

        description : typing.Optional[str]
            Description of what this condition does

        filter_set_id : typing.Optional[str]
            Filter set identifier for log filtering

        sampling_rate : typing.Optional[float]
            Sampling rate for single log conditions (0.0 to 1.0)

        time_step_minutes : typing.Optional[int]
            Time window in minutes for aggregation type conditions

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AutomationConditionDetail


        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.automations.conditions_create2(
            condition_id="condition_id",
            name="name",
            unique_organization_id="unique_organization_id",
        )
        """
        _response = self._raw_client.conditions_create2(
            condition_id,
            name=name,
            unique_organization_id=unique_organization_id,
            description=description,
            filter_set_id=filter_set_id,
            sampling_rate=sampling_rate,
            time_step_minutes=time_step_minutes,
            request_options=request_options,
        )
        return _response.data

    def conditions_update2(
        self,
        condition_id: str,
        *,
        unique_organization_id: str,
        name: str,
        condition_policy: typing.Any,
        id: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        filter_set_id: typing.Optional[str] = OMIT,
        time_step_minutes: typing.Optional[int] = OMIT,
        sampling_rate: typing.Optional[float] = OMIT,
        updated_by: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AutomationConditionUpdate:
        """
        PUT handler with superadmin lock and field protection.

        Same as patch() - checks lock and field protection before delegating.

        Parameters
        ----------
        condition_id : str

        unique_organization_id : str
            Organization identifier

        name : str
            Human-readable name for the condition

        condition_policy : typing.Any

        id : typing.Optional[str]

        description : typing.Optional[str]
            Description of what this condition does

        filter_set_id : typing.Optional[str]
            Filter set identifier for log filtering

        time_step_minutes : typing.Optional[int]
            Time window in minutes for aggregation type conditions

        sampling_rate : typing.Optional[float]
            Sampling rate for single log conditions (0.0 to 1.0)

        updated_by : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AutomationConditionUpdate


        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.automations.conditions_update2(
            condition_id="condition_id",
            unique_organization_id="x",
            name="x",
            condition_policy={"key": "value"},
        )
        """
        _response = self._raw_client.conditions_update2(
            condition_id,
            unique_organization_id=unique_organization_id,
            name=name,
            condition_policy=condition_policy,
            id=id,
            description=description,
            filter_set_id=filter_set_id,
            time_step_minutes=time_step_minutes,
            sampling_rate=sampling_rate,
            updated_by=updated_by,
            request_options=request_options,
        )
        return _response.data

    def conditions_destroy(self, condition_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        REST API view for retrieving, updating, and deleting individual automation conditions.

        This view handles:
        - GET: Retrieve a specific automation condition by condition_id
        - PUT/PATCH: Update an existing automation condition
        - DELETE: Delete an automation condition

        Superadmin: Can access any condition across all organizations.
        Regular users: Can only access conditions in their organization.

        Lookup field: id (condition_id in URL)
        Authentication: JWT token or API Key
        Permissions: Automatic via JWTAndAPIKeyAuthenticationViewMixin

        Parameters
        ----------
        condition_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.automations.conditions_destroy(
            condition_id="condition_id",
        )
        """
        _response = self._raw_client.conditions_destroy(condition_id, request_options=request_options)
        return _response.data

    def conditions_partial_update2(
        self,
        condition_id: str,
        *,
        id: typing.Optional[str] = OMIT,
        unique_organization_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        condition_policy: typing.Optional[typing.Any] = OMIT,
        filter_set_id: typing.Optional[str] = OMIT,
        time_step_minutes: typing.Optional[int] = OMIT,
        sampling_rate: typing.Optional[float] = OMIT,
        updated_by: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AutomationConditionUpdate:
        """
        PATCH handler with superadmin lock and field protection.

        Checks:
        1. Object lock (is_managed=True -> non-superadmins can't modify)
        2. Field protection (non-superadmins can't modify specific fields)

        Parameters
        ----------
        condition_id : str

        id : typing.Optional[str]

        unique_organization_id : typing.Optional[str]
            Organization identifier

        name : typing.Optional[str]
            Human-readable name for the condition

        description : typing.Optional[str]
            Description of what this condition does

        condition_policy : typing.Optional[typing.Any]
            Complex condition rules and logic stored as JSON

        filter_set_id : typing.Optional[str]
            Filter set identifier for log filtering

        time_step_minutes : typing.Optional[int]
            Time window in minutes for aggregation type conditions

        sampling_rate : typing.Optional[float]
            Sampling rate for single log conditions (0.0 to 1.0)

        updated_by : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AutomationConditionUpdate


        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.automations.conditions_partial_update2(
            condition_id="condition_id",
        )
        """
        _response = self._raw_client.conditions_partial_update2(
            condition_id,
            id=id,
            unique_organization_id=unique_organization_id,
            name=name,
            description=description,
            condition_policy=condition_policy,
            filter_set_id=filter_set_id,
            time_step_minutes=time_step_minutes,
            sampling_rate=sampling_rate,
            updated_by=updated_by,
            request_options=request_options,
        )
        return _response.data

    def conditions_simulate_create(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Simulate automation condition evaluation

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.automations.conditions_simulate_create()
        """
        _response = self._raw_client.conditions_simulate_create(request_options=request_options)
        return _response.data

    def conditions_validate_create(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Validate an automation condition policy structure

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )
        client.automations.conditions_validate_create()
        """
        _response = self._raw_client.conditions_validate_create(request_options=request_options)
        return _response.data


class AsyncAutomationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAutomationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAutomationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAutomationsClient
        """
        return self._raw_client

    async def conditions_list(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedAutomationConditionListList:
        """
        REST API view for listing and creating automation conditions.

        This view handles:
        - GET: List automation conditions with filtering and pagination
        - POST: Create new automation conditions or filter existing ones

        Superadmin: Can LIST all conditions across all organizations.
        Regular users: Can only access conditions in their organization.

        Authentication: JWT token or API Key
        Permissions: Automatic via JWTAndAPIKeyAuthenticationViewMixin
        Pagination: LogPaginator

        Parameters
        ----------
        page : typing.Optional[int]
            A page number within the paginated result set.

        page_size : typing.Optional[int]
            Number of results to return per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedAutomationConditionListList


        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.automations.conditions_list()


        asyncio.run(main())
        """
        _response = await self._raw_client.conditions_list(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def conditions_create(
        self,
        *,
        name: str,
        condition_policy: typing.Any,
        id: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        filter_set_id: typing.Optional[str] = OMIT,
        time_step_minutes: typing.Optional[int] = OMIT,
        sampling_rate: typing.Optional[float] = OMIT,
        updated_by: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AutomationConditionCreate:
        """
        Handle POST requests for both creation and filtering.

        Determines whether the request is for creating a new condition
        or filtering existing conditions based on the presence of
        creation-specific fields.

        Args:
            request: HTTP request object

        Returns:
            Response: Either creation response or filtered list response

        Parameters
        ----------
        name : str
            Human-readable name for the condition

        condition_policy : typing.Any

        id : typing.Optional[str]

        description : typing.Optional[str]
            Description of what this condition does

        filter_set_id : typing.Optional[str]
            Filter set identifier for log filtering

        time_step_minutes : typing.Optional[int]
            Time window in minutes for aggregation type conditions

        sampling_rate : typing.Optional[float]
            Sampling rate for single log conditions (0.0 to 1.0)

        updated_by : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AutomationConditionCreate


        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.automations.conditions_create(
                name="x",
                condition_policy={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.conditions_create(
            name=name,
            condition_policy=condition_policy,
            id=id,
            description=description,
            filter_set_id=filter_set_id,
            time_step_minutes=time_step_minutes,
            sampling_rate=sampling_rate,
            updated_by=updated_by,
            request_options=request_options,
        )
        return _response.data

    async def conditions_update(
        self,
        *,
        name: str,
        unique_organization_id: str,
        time_step_minutes: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AutomationConditionList:
        """
        PUT handler with superadmin lock and field protection.

        Same as patch() - checks lock and field protection before delegating.

        Parameters
        ----------
        name : str
            Human-readable name for the condition

        unique_organization_id : str
            Organization identifier

        time_step_minutes : typing.Optional[int]
            Time window in minutes for aggregation type conditions

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AutomationConditionList


        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.automations.conditions_update(
                name="name",
                unique_organization_id="unique_organization_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.conditions_update(
            name=name,
            unique_organization_id=unique_organization_id,
            time_step_minutes=time_step_minutes,
            request_options=request_options,
        )
        return _response.data

    async def conditions_partial_update(
        self,
        *,
        name: typing.Optional[str] = OMIT,
        unique_organization_id: typing.Optional[str] = OMIT,
        time_step_minutes: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AutomationConditionList:
        """
        PATCH handler with superadmin lock and field protection.

        Checks:
        1. Object lock (is_managed=True -> non-superadmins can't modify)
        2. Field protection (non-superadmins can't modify specific fields)

        Parameters
        ----------
        name : typing.Optional[str]
            Human-readable name for the condition

        unique_organization_id : typing.Optional[str]
            Organization identifier

        time_step_minutes : typing.Optional[int]
            Time window in minutes for aggregation type conditions

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AutomationConditionList


        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.automations.conditions_partial_update()


        asyncio.run(main())
        """
        _response = await self._raw_client.conditions_partial_update(
            name=name,
            unique_organization_id=unique_organization_id,
            time_step_minutes=time_step_minutes,
            request_options=request_options,
        )
        return _response.data

    async def conditions_retrieve(
        self, condition_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AutomationConditionDetail:
        """
        REST API view for retrieving, updating, and deleting individual automation conditions.

        This view handles:
        - GET: Retrieve a specific automation condition by condition_id
        - PUT/PATCH: Update an existing automation condition
        - DELETE: Delete an automation condition

        Superadmin: Can access any condition across all organizations.
        Regular users: Can only access conditions in their organization.

        Lookup field: id (condition_id in URL)
        Authentication: JWT token or API Key
        Permissions: Automatic via JWTAndAPIKeyAuthenticationViewMixin

        Parameters
        ----------
        condition_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AutomationConditionDetail


        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.automations.conditions_retrieve(
                condition_id="condition_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.conditions_retrieve(condition_id, request_options=request_options)
        return _response.data

    async def conditions_create2(
        self,
        condition_id: str,
        *,
        name: str,
        unique_organization_id: str,
        description: typing.Optional[str] = OMIT,
        filter_set_id: typing.Optional[str] = OMIT,
        sampling_rate: typing.Optional[float] = OMIT,
        time_step_minutes: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AutomationConditionDetail:
        """
        POST handler with superadmin-only field protection.

        Strips superadmin-only fields from non-superadmin requests before
        delegating to OrganizationInjectionMixin.post() for org injection.

        Parameters
        ----------
        condition_id : str

        name : str
            Human-readable name for the condition

        unique_organization_id : str
            Organization identifier

        description : typing.Optional[str]
            Description of what this condition does

        filter_set_id : typing.Optional[str]
            Filter set identifier for log filtering

        sampling_rate : typing.Optional[float]
            Sampling rate for single log conditions (0.0 to 1.0)

        time_step_minutes : typing.Optional[int]
            Time window in minutes for aggregation type conditions

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AutomationConditionDetail


        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.automations.conditions_create2(
                condition_id="condition_id",
                name="name",
                unique_organization_id="unique_organization_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.conditions_create2(
            condition_id,
            name=name,
            unique_organization_id=unique_organization_id,
            description=description,
            filter_set_id=filter_set_id,
            sampling_rate=sampling_rate,
            time_step_minutes=time_step_minutes,
            request_options=request_options,
        )
        return _response.data

    async def conditions_update2(
        self,
        condition_id: str,
        *,
        unique_organization_id: str,
        name: str,
        condition_policy: typing.Any,
        id: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        filter_set_id: typing.Optional[str] = OMIT,
        time_step_minutes: typing.Optional[int] = OMIT,
        sampling_rate: typing.Optional[float] = OMIT,
        updated_by: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AutomationConditionUpdate:
        """
        PUT handler with superadmin lock and field protection.

        Same as patch() - checks lock and field protection before delegating.

        Parameters
        ----------
        condition_id : str

        unique_organization_id : str
            Organization identifier

        name : str
            Human-readable name for the condition

        condition_policy : typing.Any

        id : typing.Optional[str]

        description : typing.Optional[str]
            Description of what this condition does

        filter_set_id : typing.Optional[str]
            Filter set identifier for log filtering

        time_step_minutes : typing.Optional[int]
            Time window in minutes for aggregation type conditions

        sampling_rate : typing.Optional[float]
            Sampling rate for single log conditions (0.0 to 1.0)

        updated_by : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AutomationConditionUpdate


        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.automations.conditions_update2(
                condition_id="condition_id",
                unique_organization_id="x",
                name="x",
                condition_policy={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.conditions_update2(
            condition_id,
            unique_organization_id=unique_organization_id,
            name=name,
            condition_policy=condition_policy,
            id=id,
            description=description,
            filter_set_id=filter_set_id,
            time_step_minutes=time_step_minutes,
            sampling_rate=sampling_rate,
            updated_by=updated_by,
            request_options=request_options,
        )
        return _response.data

    async def conditions_destroy(
        self, condition_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        REST API view for retrieving, updating, and deleting individual automation conditions.

        This view handles:
        - GET: Retrieve a specific automation condition by condition_id
        - PUT/PATCH: Update an existing automation condition
        - DELETE: Delete an automation condition

        Superadmin: Can access any condition across all organizations.
        Regular users: Can only access conditions in their organization.

        Lookup field: id (condition_id in URL)
        Authentication: JWT token or API Key
        Permissions: Automatic via JWTAndAPIKeyAuthenticationViewMixin

        Parameters
        ----------
        condition_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.automations.conditions_destroy(
                condition_id="condition_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.conditions_destroy(condition_id, request_options=request_options)
        return _response.data

    async def conditions_partial_update2(
        self,
        condition_id: str,
        *,
        id: typing.Optional[str] = OMIT,
        unique_organization_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        condition_policy: typing.Optional[typing.Any] = OMIT,
        filter_set_id: typing.Optional[str] = OMIT,
        time_step_minutes: typing.Optional[int] = OMIT,
        sampling_rate: typing.Optional[float] = OMIT,
        updated_by: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AutomationConditionUpdate:
        """
        PATCH handler with superadmin lock and field protection.

        Checks:
        1. Object lock (is_managed=True -> non-superadmins can't modify)
        2. Field protection (non-superadmins can't modify specific fields)

        Parameters
        ----------
        condition_id : str

        id : typing.Optional[str]

        unique_organization_id : typing.Optional[str]
            Organization identifier

        name : typing.Optional[str]
            Human-readable name for the condition

        description : typing.Optional[str]
            Description of what this condition does

        condition_policy : typing.Optional[typing.Any]
            Complex condition rules and logic stored as JSON

        filter_set_id : typing.Optional[str]
            Filter set identifier for log filtering

        time_step_minutes : typing.Optional[int]
            Time window in minutes for aggregation type conditions

        sampling_rate : typing.Optional[float]
            Sampling rate for single log conditions (0.0 to 1.0)

        updated_by : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AutomationConditionUpdate


        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.automations.conditions_partial_update2(
                condition_id="condition_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.conditions_partial_update2(
            condition_id,
            id=id,
            unique_organization_id=unique_organization_id,
            name=name,
            description=description,
            condition_policy=condition_policy,
            filter_set_id=filter_set_id,
            time_step_minutes=time_step_minutes,
            sampling_rate=sampling_rate,
            updated_by=updated_by,
            request_options=request_options,
        )
        return _response.data

    async def conditions_simulate_create(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Simulate automation condition evaluation

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.automations.conditions_simulate_create()


        asyncio.run(main())
        """
        _response = await self._raw_client.conditions_simulate_create(request_options=request_options)
        return _response.data

    async def conditions_validate_create(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Validate an automation condition policy structure

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_deployment_token="YOUR_RESPAN_DEPLOYMENT_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.automations.conditions_validate_create()


        asyncio.run(main())
        """
        _response = await self._raw_client.conditions_validate_create(request_options=request_options)
        return _response.data
