# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class RetrieveScoreResponseInputs(UniversalBaseModel):
    """
    Unified evaluator inputs stored with the score, when available.
    """

    input: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    Input/request evaluated.
    """

    output: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    Output/response evaluated.
    """

    metrics: typing.Optional[typing.Dict[str, typing.Any]] = None
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
