# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        GetCacheHitMetricsSummaryRequestSummaryType,
        GetCacheHitMetricsSummaryRequestTimeTick,
        GetCacheHitMetricsSummaryResponse,
        GetEvalResultsSummaryRequestSummaryType,
        GetEvalResultsSummaryRequestTimeTick,
        GetEvalResultsSummaryResponseItem,
        GetEvalResultsSummaryResponseItemAutomationName,
        GetEvalResultsSummaryResponseItemEvaluatorId,
        GetLifetimeCacheHitTotalsRequestSummaryType,
        GetLifetimeCacheHitTotalsRequestTimeTick,
        GetLifetimeCacheHitTotalsResponse,
        GetLlmMetricsSummaryRequestFetchFilters,
        GetLlmMetricsSummaryRequestSummaryType,
        GetLlmMetricsSummaryRequestTimeTick,
        GetPlatformStatsRequestBreakdownBy,
        GetQuantilesSummaryRequestSummaryType,
        GetQuantilesSummaryRequestTimeTick,
        GetQuantilesSummaryResponse,
        GetStorageVolumeSummaryRequestSummaryType,
        GetStorageVolumeSummaryResponse,
        GetTotalUsersResponse,
        GetTotalUsersResponseDataItem,
        ListActiveUsersRequestEnvironment,
        ListActiveUsersRequestSummaryType,
        ListActiveUsersRequestTimeTick,
        ListActiveUsersResponse,
        ListActiveUsersResponseSummary,
        ListCacheHitMetricsRequestSummaryType,
        ListCacheHitMetricsRequestTimeTick,
        ListCacheHitMetricsResponse,
        ListEvalResultsRequestSummaryType,
        ListEvalResultsRequestTimeTick,
        ListEvalResultsResponse,
        ListLlmMetricsRequestFetchFilters,
        ListLlmMetricsRequestSummaryType,
        ListLlmMetricsRequestTimeTick,
        ListLlmMetricsResponse,
        ListMetricsBreakdownRequestBreakdownBy,
        ListMetricsBreakdownRequestMetricsToAggregateItem,
        ListMetricsBreakdownRequestScope,
        ListMetricsBreakdownRequestSummaryType,
        ListMetricsBreakdownRequestTimeTick,
        ListMetricsBreakdownResponseValue,
        ListMetricsBreakdownResponseValueZeroItem,
        ListQuantilesRequestSummaryType,
        ListQuantilesRequestTimeTick,
        ListQuantilesResponse,
        ListStorageVolumeRequestSummaryType,
        ListStorageVolumeResponse,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "GetCacheHitMetricsSummaryRequestSummaryType": ".types",
    "GetCacheHitMetricsSummaryRequestTimeTick": ".types",
    "GetCacheHitMetricsSummaryResponse": ".types",
    "GetEvalResultsSummaryRequestSummaryType": ".types",
    "GetEvalResultsSummaryRequestTimeTick": ".types",
    "GetEvalResultsSummaryResponseItem": ".types",
    "GetEvalResultsSummaryResponseItemAutomationName": ".types",
    "GetEvalResultsSummaryResponseItemEvaluatorId": ".types",
    "GetLifetimeCacheHitTotalsRequestSummaryType": ".types",
    "GetLifetimeCacheHitTotalsRequestTimeTick": ".types",
    "GetLifetimeCacheHitTotalsResponse": ".types",
    "GetLlmMetricsSummaryRequestFetchFilters": ".types",
    "GetLlmMetricsSummaryRequestSummaryType": ".types",
    "GetLlmMetricsSummaryRequestTimeTick": ".types",
    "GetPlatformStatsRequestBreakdownBy": ".types",
    "GetQuantilesSummaryRequestSummaryType": ".types",
    "GetQuantilesSummaryRequestTimeTick": ".types",
    "GetQuantilesSummaryResponse": ".types",
    "GetStorageVolumeSummaryRequestSummaryType": ".types",
    "GetStorageVolumeSummaryResponse": ".types",
    "GetTotalUsersResponse": ".types",
    "GetTotalUsersResponseDataItem": ".types",
    "ListActiveUsersRequestEnvironment": ".types",
    "ListActiveUsersRequestSummaryType": ".types",
    "ListActiveUsersRequestTimeTick": ".types",
    "ListActiveUsersResponse": ".types",
    "ListActiveUsersResponseSummary": ".types",
    "ListCacheHitMetricsRequestSummaryType": ".types",
    "ListCacheHitMetricsRequestTimeTick": ".types",
    "ListCacheHitMetricsResponse": ".types",
    "ListEvalResultsRequestSummaryType": ".types",
    "ListEvalResultsRequestTimeTick": ".types",
    "ListEvalResultsResponse": ".types",
    "ListLlmMetricsRequestFetchFilters": ".types",
    "ListLlmMetricsRequestSummaryType": ".types",
    "ListLlmMetricsRequestTimeTick": ".types",
    "ListLlmMetricsResponse": ".types",
    "ListMetricsBreakdownRequestBreakdownBy": ".types",
    "ListMetricsBreakdownRequestMetricsToAggregateItem": ".types",
    "ListMetricsBreakdownRequestScope": ".types",
    "ListMetricsBreakdownRequestSummaryType": ".types",
    "ListMetricsBreakdownRequestTimeTick": ".types",
    "ListMetricsBreakdownResponseValue": ".types",
    "ListMetricsBreakdownResponseValueZeroItem": ".types",
    "ListQuantilesRequestSummaryType": ".types",
    "ListQuantilesRequestTimeTick": ".types",
    "ListQuantilesResponse": ".types",
    "ListStorageVolumeRequestSummaryType": ".types",
    "ListStorageVolumeResponse": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "GetCacheHitMetricsSummaryRequestSummaryType",
    "GetCacheHitMetricsSummaryRequestTimeTick",
    "GetCacheHitMetricsSummaryResponse",
    "GetEvalResultsSummaryRequestSummaryType",
    "GetEvalResultsSummaryRequestTimeTick",
    "GetEvalResultsSummaryResponseItem",
    "GetEvalResultsSummaryResponseItemAutomationName",
    "GetEvalResultsSummaryResponseItemEvaluatorId",
    "GetLifetimeCacheHitTotalsRequestSummaryType",
    "GetLifetimeCacheHitTotalsRequestTimeTick",
    "GetLifetimeCacheHitTotalsResponse",
    "GetLlmMetricsSummaryRequestFetchFilters",
    "GetLlmMetricsSummaryRequestSummaryType",
    "GetLlmMetricsSummaryRequestTimeTick",
    "GetPlatformStatsRequestBreakdownBy",
    "GetQuantilesSummaryRequestSummaryType",
    "GetQuantilesSummaryRequestTimeTick",
    "GetQuantilesSummaryResponse",
    "GetStorageVolumeSummaryRequestSummaryType",
    "GetStorageVolumeSummaryResponse",
    "GetTotalUsersResponse",
    "GetTotalUsersResponseDataItem",
    "ListActiveUsersRequestEnvironment",
    "ListActiveUsersRequestSummaryType",
    "ListActiveUsersRequestTimeTick",
    "ListActiveUsersResponse",
    "ListActiveUsersResponseSummary",
    "ListCacheHitMetricsRequestSummaryType",
    "ListCacheHitMetricsRequestTimeTick",
    "ListCacheHitMetricsResponse",
    "ListEvalResultsRequestSummaryType",
    "ListEvalResultsRequestTimeTick",
    "ListEvalResultsResponse",
    "ListLlmMetricsRequestFetchFilters",
    "ListLlmMetricsRequestSummaryType",
    "ListLlmMetricsRequestTimeTick",
    "ListLlmMetricsResponse",
    "ListMetricsBreakdownRequestBreakdownBy",
    "ListMetricsBreakdownRequestMetricsToAggregateItem",
    "ListMetricsBreakdownRequestScope",
    "ListMetricsBreakdownRequestSummaryType",
    "ListMetricsBreakdownRequestTimeTick",
    "ListMetricsBreakdownResponseValue",
    "ListMetricsBreakdownResponseValueZeroItem",
    "ListQuantilesRequestSummaryType",
    "ListQuantilesRequestTimeTick",
    "ListQuantilesResponse",
    "ListStorageVolumeRequestSummaryType",
    "ListStorageVolumeResponse",
]
