# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawOpenAiBatchClient, RawOpenAiBatchClient
from .types.cancel_batch_response import CancelBatchResponse
from .types.create_batch_request_completion_window import CreateBatchRequestCompletionWindow
from .types.create_batch_request_endpoint import CreateBatchRequestEndpoint
from .types.create_batch_response import CreateBatchResponse
from .types.delete_file_response import DeleteFileResponse
from .types.filter_batch_jobs_response import FilterBatchJobsResponse
from .types.filter_batch_jobs_response_results_item import FilterBatchJobsResponseResultsItem
from .types.filter_batch_jobs_summary_response import FilterBatchJobsSummaryResponse
from .types.list_files_response import ListFilesResponse
from .types.retrieve_batch_response import RetrieveBatchResponse
from .types.retrieve_file_response import RetrieveFileResponse
from .types.upload_file_response import UploadFileResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class OpenAiBatchClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOpenAiBatchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOpenAiBatchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOpenAiBatchClient
        """
        return self._raw_client

    def list_files(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListFilesResponse:
        """
        List files from the upstream OpenAI Files API using the authenticated organization key's OpenAI credentials.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListFilesResponse
            List of files.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )
        client.open_ai_batch.list_files()
        """
        _response = self._raw_client.list_files(request_options=request_options)
        return _response.data

    def upload_file(
        self, *, file: core.File, purpose: str, request_options: typing.Optional[RequestOptions] = None
    ) -> UploadFileResponse:
        """
        Upload a file to the upstream OpenAI Files API. Batch jobs use JSONL files with `purpose=batch`.

        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        purpose : str
            File purpose.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadFileResponse
            Uploaded file.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )
        client.open_ai_batch.upload_file(
            purpose="purpose",
        )
        """
        _response = self._raw_client.upload_file(file=file, purpose=purpose, request_options=request_options)
        return _response.data

    def retrieve_file(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RetrieveFileResponse:
        """
        Retrieve metadata for a file from the upstream OpenAI Files API.

        Parameters
        ----------
        file_id : str
            OpenAI file ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetrieveFileResponse
            File details.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )
        client.open_ai_batch.retrieve_file(
            file_id="file-abc123",
        )
        """
        _response = self._raw_client.retrieve_file(file_id, request_options=request_options)
        return _response.data

    def delete_file(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteFileResponse:
        """
        Delete a file from the upstream OpenAI Files API.

        Parameters
        ----------
        file_id : str
            OpenAI file ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteFileResponse
            Deleted file.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )
        client.open_ai_batch.delete_file(
            file_id="file-abc123",
        )
        """
        _response = self._raw_client.delete_file(file_id, request_options=request_options)
        return _response.data

    def retrieve_file_content(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        Download file content. Batch output files are returned as JSONL.

        Parameters
        ----------
        file_id : str
            OpenAI file ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            File content.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )
        client.open_ai_batch.retrieve_file_content(
            file_id="file_id",
        )
        """
        with self._raw_client.retrieve_file_content(file_id, request_options=request_options) as r:
            yield from r.data

    def create_batch(
        self,
        *,
        input_file_id: str,
        endpoint: CreateBatchRequestEndpoint,
        completion_window: CreateBatchRequestCompletionWindow,
        data_respan_params: typing.Optional[str] = None,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        customer_identifier: typing.Optional[str] = OMIT,
        custom_identifier: typing.Optional[str] = OMIT,
        thread_identifier: typing.Optional[str] = OMIT,
        environment: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateBatchResponse:
        """
        Create an OpenAI-compatible batch processing job from an uploaded JSONL file.

        Parameters
        ----------
        input_file_id : str
            Uploaded JSONL file ID.

        endpoint : CreateBatchRequestEndpoint
            Endpoint each JSONL request targets.

        completion_window : CreateBatchRequestCompletionWindow

        data_respan_params : typing.Optional[str]
            Base64-encoded JSON object of Respan request parameters. Legacy `X-Data-Keywordsai-Params` is still accepted.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Custom metadata for tracking.

        customer_identifier : typing.Optional[str]
            End-user identifier for logging.

        custom_identifier : typing.Optional[str]
            Custom identifier for querying.

        thread_identifier : typing.Optional[str]
            Conversation thread identifier.

        environment : typing.Optional[str]
            Environment tag.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateBatchResponse
            Created batch.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )
        client.open_ai_batch.create_batch(
            input_file_id="file-abc123",
            endpoint="/v1/chat/completions",
            completion_window="24h",
        )
        """
        _response = self._raw_client.create_batch(
            input_file_id=input_file_id,
            endpoint=endpoint,
            completion_window=completion_window,
            data_respan_params=data_respan_params,
            metadata=metadata,
            customer_identifier=customer_identifier,
            custom_identifier=custom_identifier,
            thread_identifier=thread_identifier,
            environment=environment,
            request_options=request_options,
        )
        return _response.data

    def retrieve_batch(
        self,
        batch_id: str,
        *,
        data_respan_params: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RetrieveBatchResponse:
        """
        Retrieve an OpenAI-compatible batch job by ID.

        Parameters
        ----------
        batch_id : str
            Batch ID.

        data_respan_params : typing.Optional[str]
            Base64-encoded JSON object of Respan request parameters. Legacy `X-Data-Keywordsai-Params` is still accepted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetrieveBatchResponse
            Batch details.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )
        client.open_ai_batch.retrieve_batch(
            batch_id="batch_abc123",
        )
        """
        _response = self._raw_client.retrieve_batch(
            batch_id, data_respan_params=data_respan_params, request_options=request_options
        )
        return _response.data

    def cancel_batch(
        self,
        batch_id: str,
        *,
        request: typing.Dict[str, typing.Any],
        data_respan_params: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CancelBatchResponse:
        """
        Cancel an in-progress OpenAI-compatible batch. Already completed requests are not affected.

        Parameters
        ----------
        batch_id : str
            Batch ID.

        request : typing.Dict[str, typing.Any]

        data_respan_params : typing.Optional[str]
            Base64-encoded JSON object of Respan request parameters. Legacy `X-Data-Keywordsai-Params` is still accepted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelBatchResponse
            Batch cancellation initiated.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )
        client.open_ai_batch.cancel_batch(
            batch_id="batch_abc123",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.cancel_batch(
            batch_id, request=request, data_respan_params=data_respan_params, request_options=request_options
        )
        return _response.data

    def filter_batch_jobs(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        status: typing.Optional[str] = None,
        provider_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[FilterBatchJobsResponseResultsItem, FilterBatchJobsResponse]:
        """
        Dashboard-authenticated POST-for-filtering route for batch jobs. The backend delegates POST to GET, so filters are query parameters (`status`, `provider_id`) and request bodies are ignored.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number.

        page_size : typing.Optional[int]
            Number of results per page. Maximum 100.

        status : typing.Optional[str]
            Filter dashboard batch jobs by normalized batch status.

        provider_id : typing.Optional[str]
            Filter dashboard batch jobs by provider ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[FilterBatchJobsResponseResultsItem, FilterBatchJobsResponse]
            Paginated filtered list of batch jobs.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )
        response = client.open_ai_batch.filter_batch_jobs(
            status="completed",
            provider_id="openai",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.filter_batch_jobs(
            page=page, page_size=page_size, status=status, provider_id=provider_id, request_options=request_options
        )

    def filter_batch_jobs_summary(
        self,
        *,
        status: typing.Optional[str] = None,
        provider_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FilterBatchJobsSummaryResponse:
        """
        Dashboard-authenticated extension for aggregated batch job statistics. The backend delegates POST to GET, so filters are query parameters (`status`, `provider_id`) and request bodies are ignored.

        Parameters
        ----------
        status : typing.Optional[str]
            Filter dashboard batch jobs by normalized batch status.

        provider_id : typing.Optional[str]
            Filter dashboard batch jobs by provider ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FilterBatchJobsSummaryResponse
            Batch job summary.

        Examples
        --------
        from respan import RespanClient

        client = RespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )
        client.open_ai_batch.filter_batch_jobs_summary(
            status="completed",
            provider_id="openai",
        )
        """
        _response = self._raw_client.filter_batch_jobs_summary(
            status=status, provider_id=provider_id, request_options=request_options
        )
        return _response.data


class AsyncOpenAiBatchClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOpenAiBatchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOpenAiBatchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOpenAiBatchClient
        """
        return self._raw_client

    async def list_files(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListFilesResponse:
        """
        List files from the upstream OpenAI Files API using the authenticated organization key's OpenAI credentials.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListFilesResponse
            List of files.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )


        async def main() -> None:
            await client.open_ai_batch.list_files()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_files(request_options=request_options)
        return _response.data

    async def upload_file(
        self, *, file: core.File, purpose: str, request_options: typing.Optional[RequestOptions] = None
    ) -> UploadFileResponse:
        """
        Upload a file to the upstream OpenAI Files API. Batch jobs use JSONL files with `purpose=batch`.

        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        purpose : str
            File purpose.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadFileResponse
            Uploaded file.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )


        async def main() -> None:
            await client.open_ai_batch.upload_file(
                purpose="purpose",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.upload_file(file=file, purpose=purpose, request_options=request_options)
        return _response.data

    async def retrieve_file(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RetrieveFileResponse:
        """
        Retrieve metadata for a file from the upstream OpenAI Files API.

        Parameters
        ----------
        file_id : str
            OpenAI file ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetrieveFileResponse
            File details.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )


        async def main() -> None:
            await client.open_ai_batch.retrieve_file(
                file_id="file-abc123",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve_file(file_id, request_options=request_options)
        return _response.data

    async def delete_file(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteFileResponse:
        """
        Delete a file from the upstream OpenAI Files API.

        Parameters
        ----------
        file_id : str
            OpenAI file ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteFileResponse
            Deleted file.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )


        async def main() -> None:
            await client.open_ai_batch.delete_file(
                file_id="file-abc123",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_file(file_id, request_options=request_options)
        return _response.data

    async def retrieve_file_content(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Download file content. Batch output files are returned as JSONL.

        Parameters
        ----------
        file_id : str
            OpenAI file ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            File content.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )


        async def main() -> None:
            await client.open_ai_batch.retrieve_file_content(
                file_id="file_id",
            )


        asyncio.run(main())
        """
        async with self._raw_client.retrieve_file_content(file_id, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk

    async def create_batch(
        self,
        *,
        input_file_id: str,
        endpoint: CreateBatchRequestEndpoint,
        completion_window: CreateBatchRequestCompletionWindow,
        data_respan_params: typing.Optional[str] = None,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        customer_identifier: typing.Optional[str] = OMIT,
        custom_identifier: typing.Optional[str] = OMIT,
        thread_identifier: typing.Optional[str] = OMIT,
        environment: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateBatchResponse:
        """
        Create an OpenAI-compatible batch processing job from an uploaded JSONL file.

        Parameters
        ----------
        input_file_id : str
            Uploaded JSONL file ID.

        endpoint : CreateBatchRequestEndpoint
            Endpoint each JSONL request targets.

        completion_window : CreateBatchRequestCompletionWindow

        data_respan_params : typing.Optional[str]
            Base64-encoded JSON object of Respan request parameters. Legacy `X-Data-Keywordsai-Params` is still accepted.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Custom metadata for tracking.

        customer_identifier : typing.Optional[str]
            End-user identifier for logging.

        custom_identifier : typing.Optional[str]
            Custom identifier for querying.

        thread_identifier : typing.Optional[str]
            Conversation thread identifier.

        environment : typing.Optional[str]
            Environment tag.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateBatchResponse
            Created batch.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )


        async def main() -> None:
            await client.open_ai_batch.create_batch(
                input_file_id="file-abc123",
                endpoint="/v1/chat/completions",
                completion_window="24h",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_batch(
            input_file_id=input_file_id,
            endpoint=endpoint,
            completion_window=completion_window,
            data_respan_params=data_respan_params,
            metadata=metadata,
            customer_identifier=customer_identifier,
            custom_identifier=custom_identifier,
            thread_identifier=thread_identifier,
            environment=environment,
            request_options=request_options,
        )
        return _response.data

    async def retrieve_batch(
        self,
        batch_id: str,
        *,
        data_respan_params: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RetrieveBatchResponse:
        """
        Retrieve an OpenAI-compatible batch job by ID.

        Parameters
        ----------
        batch_id : str
            Batch ID.

        data_respan_params : typing.Optional[str]
            Base64-encoded JSON object of Respan request parameters. Legacy `X-Data-Keywordsai-Params` is still accepted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetrieveBatchResponse
            Batch details.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )


        async def main() -> None:
            await client.open_ai_batch.retrieve_batch(
                batch_id="batch_abc123",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve_batch(
            batch_id, data_respan_params=data_respan_params, request_options=request_options
        )
        return _response.data

    async def cancel_batch(
        self,
        batch_id: str,
        *,
        request: typing.Dict[str, typing.Any],
        data_respan_params: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CancelBatchResponse:
        """
        Cancel an in-progress OpenAI-compatible batch. Already completed requests are not affected.

        Parameters
        ----------
        batch_id : str
            Batch ID.

        request : typing.Dict[str, typing.Any]

        data_respan_params : typing.Optional[str]
            Base64-encoded JSON object of Respan request parameters. Legacy `X-Data-Keywordsai-Params` is still accepted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelBatchResponse
            Batch cancellation initiated.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )


        async def main() -> None:
            await client.open_ai_batch.cancel_batch(
                batch_id="batch_abc123",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_batch(
            batch_id, request=request, data_respan_params=data_respan_params, request_options=request_options
        )
        return _response.data

    async def filter_batch_jobs(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        status: typing.Optional[str] = None,
        provider_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[FilterBatchJobsResponseResultsItem, FilterBatchJobsResponse]:
        """
        Dashboard-authenticated POST-for-filtering route for batch jobs. The backend delegates POST to GET, so filters are query parameters (`status`, `provider_id`) and request bodies are ignored.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number.

        page_size : typing.Optional[int]
            Number of results per page. Maximum 100.

        status : typing.Optional[str]
            Filter dashboard batch jobs by normalized batch status.

        provider_id : typing.Optional[str]
            Filter dashboard batch jobs by provider ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[FilterBatchJobsResponseResultsItem, FilterBatchJobsResponse]
            Paginated filtered list of batch jobs.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )


        async def main() -> None:
            response = await client.open_ai_batch.filter_batch_jobs(
                status="completed",
                provider_id="openai",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.filter_batch_jobs(
            page=page, page_size=page_size, status=status, provider_id=provider_id, request_options=request_options
        )

    async def filter_batch_jobs_summary(
        self,
        *,
        status: typing.Optional[str] = None,
        provider_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FilterBatchJobsSummaryResponse:
        """
        Dashboard-authenticated extension for aggregated batch job statistics. The backend delegates POST to GET, so filters are query parameters (`status`, `provider_id`) and request bodies are ignored.

        Parameters
        ----------
        status : typing.Optional[str]
            Filter dashboard batch jobs by normalized batch status.

        provider_id : typing.Optional[str]
            Filter dashboard batch jobs by provider ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FilterBatchJobsSummaryResponse
            Batch job summary.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient

        client = AsyncRespanClient(
            respan_api_key="YOUR_RESPAN_API_KEY",
        )


        async def main() -> None:
            await client.open_ai_batch.filter_batch_jobs_summary(
                status="completed",
                provider_id="openai",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.filter_batch_jobs_summary(
            status=status, provider_id=provider_id, request_options=request_options
        )
        return _response.data
