# This file was auto-generated by Fern from our API Definition.

import typing

ListBatchesResponseDataItemStatus = typing.Union[
    typing.Literal[
        "validating",
        "pending",
        "in_progress",
        "finalizing",
        "completed",
        "failed",
        "expired",
        "cancelling",
        "cancelled",
    ],
    typing.Any,
]
