# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..types.column_type_enum import ColumnTypeEnum
from ..types.dataset_logs_bulk_create_response import DatasetLogsBulkCreateResponse
from ..types.generation_method_enum import GenerationMethodEnum
from ..types.paginated_playground_list_list import PaginatedPlaygroundListList
from ..types.playground_column_create import PlaygroundColumnCreate
from ..types.playground_column_detail import PlaygroundColumnDetail
from ..types.playground_column_list import PlaygroundColumnList
from ..types.playground_create import PlaygroundCreate
from ..types.playground_detail import PlaygroundDetail
from ..types.playground_rows_list_response import PlaygroundRowsListResponse
from ..types.playground_rows_summary import PlaygroundRowsSummary
from ..types.playground_run import PlaygroundRun
from ..types.source_type775enum import SourceType775Enum

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawPlaygroundsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def api_playgrounds_list(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaginatedPlaygroundListList]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        page : typing.Optional[int]
            A page number within the paginated result set.

        page_size : typing.Optional[int]
            Number of results to return per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaginatedPlaygroundListList]

        """
        _response = self._client_wrapper.httpx_client.request(
            "api/playgrounds/",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedPlaygroundListList,
                    parse_obj_as(
                        type_=PaginatedPlaygroundListList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_create(
        self,
        *,
        name: str,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PlaygroundCreate]:
        """
        POST handler with superadmin-only field protection.

        Strips superadmin-only fields from non-superadmin requests before
        delegating to OrganizationInjectionMixin.post() for org injection.

        Parameters
        ----------
        name : str

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PlaygroundCreate]

        """
        _response = self._client_wrapper.httpx_client.request(
            "api/playgrounds/",
            method="POST",
            json={
                "name": name,
                "description": description,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundCreate,
                    parse_obj_as(
                        type_=PlaygroundCreate,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_retrieve(
        self, playground_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PlaygroundDetail]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        playground_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PlaygroundDetail]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundDetail,
                    parse_obj_as(
                        type_=PlaygroundDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_update(
        self,
        playground_id: str,
        *,
        name: str,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PlaygroundDetail]:
        """
        PUT handler with superadmin lock and field protection.

        Same as patch() - checks lock and field protection before delegating.

        Parameters
        ----------
        playground_id : str

        name : str

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PlaygroundDetail]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/",
            method="PUT",
            json={
                "name": name,
                "description": description,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundDetail,
                    parse_obj_as(
                        type_=PlaygroundDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_destroy(
        self, playground_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        playground_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_partial_update(
        self,
        playground_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PlaygroundDetail]:
        """
        PATCH handler with superadmin lock and field protection.

        Checks:
        1. Object lock (is_managed=True -> non-superadmins can't modify)
        2. Field protection (non-superadmins can't modify specific fields)

        Parameters
        ----------
        playground_id : str

        name : typing.Optional[str]

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PlaygroundDetail]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/",
            method="PATCH",
            json={
                "name": name,
                "description": description,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundDetail,
                    parse_obj_as(
                        type_=PlaygroundDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_columns_list(
        self, playground_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.List[PlaygroundColumnList]]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        playground_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[PlaygroundColumnList]]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/columns/",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[PlaygroundColumnList],
                    parse_obj_as(
                        type_=typing.List[PlaygroundColumnList],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_columns_create(
        self,
        playground_id: str,
        *,
        playground: str,
        name: str,
        order: typing.Optional[int] = OMIT,
        column_type: typing.Optional[ColumnTypeEnum] = OMIT,
        source_type: typing.Optional[SourceType775Enum] = OMIT,
        linked_prompt_id: typing.Optional[str] = OMIT,
        linked_prompt_version: typing.Optional[int] = OMIT,
        prompt: typing.Optional[typing.Any] = OMIT,
        is_archived: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PlaygroundColumnCreate]:
        """
        Default POST handler with automatic organization injection.

        For CREATE operations:
        - Superadmins can specify organization_id in request body (API key only)
        - Regular users always use their own organization

        Override this method for:
        - POST-for-filtering pattern (delegate to self.get())
        - Custom pre-create validation

        Note: ``inject_target_organization`` is a DEPRECATED ``request.data``-mutating
        shim kept for backward-compat during the DEV-9410 migration. The blessed
        path stamps org via ``get_create_save_kwargs`` → ``perform_create`` → a
        ``read_only`` serializer field. The shim (and these overrides' reliance on
        it) is removed in C18 (DEV-9430) once every view's org field is read_only.

        Parameters
        ----------
        playground_id : str

        playground : str

        name : str

        order : typing.Optional[int]

        column_type : typing.Optional[ColumnTypeEnum]

        source_type : typing.Optional[SourceType775Enum]

        linked_prompt_id : typing.Optional[str]

        linked_prompt_version : typing.Optional[int]

        prompt : typing.Optional[typing.Any]

        is_archived : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PlaygroundColumnCreate]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/columns/",
            method="POST",
            json={
                "playground": playground,
                "name": name,
                "order": order,
                "column_type": column_type,
                "source_type": source_type,
                "linked_prompt_id": linked_prompt_id,
                "linked_prompt_version": linked_prompt_version,
                "prompt": prompt,
                "is_archived": is_archived,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundColumnCreate,
                    parse_obj_as(
                        type_=PlaygroundColumnCreate,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_columns_retrieve(
        self, playground_id: str, column_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PlaygroundColumnDetail]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        playground_id : str

        column_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PlaygroundColumnDetail]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/columns/{jsonable_encoder(column_id)}/",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundColumnDetail,
                    parse_obj_as(
                        type_=PlaygroundColumnDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_columns_update(
        self,
        playground_id: str,
        column_id: str,
        *,
        name: str,
        order: typing.Optional[int] = OMIT,
        column_type: typing.Optional[ColumnTypeEnum] = OMIT,
        source_type: typing.Optional[SourceType775Enum] = OMIT,
        linked_prompt_id: typing.Optional[str] = OMIT,
        linked_prompt_version: typing.Optional[int] = OMIT,
        prompt: typing.Optional[typing.Any] = OMIT,
        is_archived: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PlaygroundColumnDetail]:
        """
        Default PUT handler with automatic organization injection.

        Same behavior as patch() - preserves ownership for superadmins,
        forces user's org for regular users.

        Parameters
        ----------
        playground_id : str

        column_id : str

        name : str

        order : typing.Optional[int]

        column_type : typing.Optional[ColumnTypeEnum]

        source_type : typing.Optional[SourceType775Enum]

        linked_prompt_id : typing.Optional[str]

        linked_prompt_version : typing.Optional[int]

        prompt : typing.Optional[typing.Any]

        is_archived : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PlaygroundColumnDetail]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/columns/{jsonable_encoder(column_id)}/",
            method="PUT",
            json={
                "name": name,
                "order": order,
                "column_type": column_type,
                "source_type": source_type,
                "linked_prompt_id": linked_prompt_id,
                "linked_prompt_version": linked_prompt_version,
                "prompt": prompt,
                "is_archived": is_archived,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundColumnDetail,
                    parse_obj_as(
                        type_=PlaygroundColumnDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_columns_destroy(
        self, playground_id: str, column_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        playground_id : str

        column_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/columns/{jsonable_encoder(column_id)}/",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_columns_partial_update(
        self,
        playground_id: str,
        column_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        order: typing.Optional[int] = OMIT,
        column_type: typing.Optional[ColumnTypeEnum] = OMIT,
        source_type: typing.Optional[SourceType775Enum] = OMIT,
        linked_prompt_id: typing.Optional[str] = OMIT,
        linked_prompt_version: typing.Optional[int] = OMIT,
        prompt: typing.Optional[typing.Any] = OMIT,
        is_archived: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PlaygroundColumnDetail]:
        """
        Default PATCH handler with automatic organization injection.

        For UPDATE operations:
        - Superadmins preserve original ownership (org fields removed from request)
        - Regular users are forced to their own organization

        Override this method only for custom pre-update logic.

        Parameters
        ----------
        playground_id : str

        column_id : str

        name : typing.Optional[str]

        order : typing.Optional[int]

        column_type : typing.Optional[ColumnTypeEnum]

        source_type : typing.Optional[SourceType775Enum]

        linked_prompt_id : typing.Optional[str]

        linked_prompt_version : typing.Optional[int]

        prompt : typing.Optional[typing.Any]

        is_archived : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PlaygroundColumnDetail]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/columns/{jsonable_encoder(column_id)}/",
            method="PATCH",
            json={
                "name": name,
                "order": order,
                "column_type": column_type,
                "source_type": source_type,
                "linked_prompt_id": linked_prompt_id,
                "linked_prompt_version": linked_prompt_version,
                "prompt": prompt,
                "is_archived": is_archived,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundColumnDetail,
                    parse_obj_as(
                        type_=PlaygroundColumnDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_rows_bulk_create(
        self,
        playground_id: str,
        *,
        logs: typing.Sequence[typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DatasetLogsBulkCreateResponse]:
        """
        Default POST handler with automatic organization injection.

        For CREATE operations:
        - Superadmins can specify organization_id in request body (API key only)
        - Regular users always use their own organization

        Override this method for:
        - POST-for-filtering pattern (delegate to self.get())
        - Custom pre-create validation

        Note: ``inject_target_organization`` is a DEPRECATED ``request.data``-mutating
        shim kept for backward-compat during the DEV-9410 migration. The blessed
        path stamps org via ``get_create_save_kwargs`` → ``perform_create`` → a
        ``read_only`` serializer field. The shim (and these overrides' reliance on
        it) is removed in C18 (DEV-9430) once every view's org field is read_only.

        Parameters
        ----------
        playground_id : str

        logs : typing.Sequence[typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DatasetLogsBulkCreateResponse]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/rows/bulk/",
            method="POST",
            json={
                "logs": logs,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DatasetLogsBulkCreateResponse,
                    parse_obj_as(
                        type_=DatasetLogsBulkCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_rows_list_list(
        self,
        playground_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort_by: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PlaygroundRowsListResponse]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        playground_id : str

        page : typing.Optional[int]
            Page number for grouped Playground rows.

        page_size : typing.Optional[int]
            Page size for grouped Playground rows.

        sort_by : typing.Optional[str]
            Sort grouped rows. Defaults to comparison_key. Supports row fields and cell sorting via cells__<experiment_id>.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PlaygroundRowsListResponse]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/rows/list/",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
                "sort_by": sort_by,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundRowsListResponse,
                    parse_obj_as(
                        type_=PlaygroundRowsListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_rows_list_filtered(
        self,
        playground_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort_by: typing.Optional[str] = None,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PlaygroundRowsListResponse]:
        """
        Default POST handler with automatic organization injection.

        For CREATE operations:
        - Superadmins can specify organization_id in request body (API key only)
        - Regular users always use their own organization

        Override this method for:
        - POST-for-filtering pattern (delegate to self.get())
        - Custom pre-create validation

        Note: ``inject_target_organization`` is a DEPRECATED ``request.data``-mutating
        shim kept for backward-compat during the DEV-9410 migration. The blessed
        path stamps org via ``get_create_save_kwargs`` → ``perform_create`` → a
        ``read_only`` serializer field. The shim (and these overrides' reliance on
        it) is removed in C18 (DEV-9430) once every view's org field is read_only.

        Parameters
        ----------
        playground_id : str

        page : typing.Optional[int]
            Page number for grouped Playground rows.

        page_size : typing.Optional[int]
            Page size for grouped Playground rows.

        sort_by : typing.Optional[str]
            Sort grouped rows. Defaults to comparison_key. Supports row fields and cell sorting via cells__<experiment_id>.

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Filter parameters keyed by metric name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PlaygroundRowsListResponse]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/rows/list/",
            method="POST",
            params={
                "page": page,
                "page_size": page_size,
                "sort_by": sort_by,
            },
            json={
                "filters": filters,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundRowsListResponse,
                    parse_obj_as(
                        type_=PlaygroundRowsListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_rows_summary_retrieve(
        self, playground_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PlaygroundRowsSummary]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        playground_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PlaygroundRowsSummary]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/rows/summary/",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundRowsSummary,
                    parse_obj_as(
                        type_=PlaygroundRowsSummary,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_rows_summary_filtered(
        self,
        playground_id: str,
        *,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PlaygroundRowsSummary]:
        """
        Default POST handler with automatic organization injection.

        For CREATE operations:
        - Superadmins can specify organization_id in request body (API key only)
        - Regular users always use their own organization

        Override this method for:
        - POST-for-filtering pattern (delegate to self.get())
        - Custom pre-create validation

        Note: ``inject_target_organization`` is a DEPRECATED ``request.data``-mutating
        shim kept for backward-compat during the DEV-9410 migration. The blessed
        path stamps org via ``get_create_save_kwargs`` → ``perform_create`` → a
        ``read_only`` serializer field. The shim (and these overrides' reliance on
        it) is removed in C18 (DEV-9430) once every view's org field is read_only.

        Parameters
        ----------
        playground_id : str

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Filter parameters keyed by metric name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PlaygroundRowsSummary]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/rows/summary/",
            method="POST",
            json={
                "filters": filters,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundRowsSummary,
                    parse_obj_as(
                        type_=PlaygroundRowsSummary,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_runs_retrieve(
        self, playground_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PlaygroundRun]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        playground_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PlaygroundRun]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/runs/",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundRun,
                    parse_obj_as(
                        type_=PlaygroundRun,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_playgrounds_runs_create(
        self,
        playground_id: str,
        *,
        column_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        row_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        batch_size: typing.Optional[int] = OMIT,
        concurrency: typing.Optional[int] = OMIT,
        is_tracing_enabled: typing.Optional[bool] = OMIT,
        generation_method: typing.Optional[GenerationMethodEnum] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PlaygroundRun]:
        """
        Default POST handler with automatic organization injection.

        For CREATE operations:
        - Superadmins can specify organization_id in request body (API key only)
        - Regular users always use their own organization

        Override this method for:
        - POST-for-filtering pattern (delegate to self.get())
        - Custom pre-create validation

        Note: ``inject_target_organization`` is a DEPRECATED ``request.data``-mutating
        shim kept for backward-compat during the DEV-9410 migration. The blessed
        path stamps org via ``get_create_save_kwargs`` → ``perform_create`` → a
        ``read_only`` serializer field. The shim (and these overrides' reliance on
        it) is removed in C18 (DEV-9430) once every view's org field is read_only.

        Parameters
        ----------
        playground_id : str

        column_ids : typing.Optional[typing.Sequence[str]]

        row_ids : typing.Optional[typing.Sequence[str]]

        batch_size : typing.Optional[int]

        concurrency : typing.Optional[int]

        is_tracing_enabled : typing.Optional[bool]

        generation_method : typing.Optional[GenerationMethodEnum]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PlaygroundRun]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/runs/",
            method="POST",
            json={
                "column_ids": column_ids,
                "row_ids": row_ids,
                "batch_size": batch_size,
                "concurrency": concurrency,
                "is_tracing_enabled": is_tracing_enabled,
                "generation_method": generation_method,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundRun,
                    parse_obj_as(
                        type_=PlaygroundRun,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawPlaygroundsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def api_playgrounds_list(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaginatedPlaygroundListList]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        page : typing.Optional[int]
            A page number within the paginated result set.

        page_size : typing.Optional[int]
            Number of results to return per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaginatedPlaygroundListList]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/playgrounds/",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedPlaygroundListList,
                    parse_obj_as(
                        type_=PaginatedPlaygroundListList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_create(
        self,
        *,
        name: str,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PlaygroundCreate]:
        """
        POST handler with superadmin-only field protection.

        Strips superadmin-only fields from non-superadmin requests before
        delegating to OrganizationInjectionMixin.post() for org injection.

        Parameters
        ----------
        name : str

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PlaygroundCreate]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/playgrounds/",
            method="POST",
            json={
                "name": name,
                "description": description,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundCreate,
                    parse_obj_as(
                        type_=PlaygroundCreate,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_retrieve(
        self, playground_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PlaygroundDetail]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        playground_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PlaygroundDetail]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundDetail,
                    parse_obj_as(
                        type_=PlaygroundDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_update(
        self,
        playground_id: str,
        *,
        name: str,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PlaygroundDetail]:
        """
        PUT handler with superadmin lock and field protection.

        Same as patch() - checks lock and field protection before delegating.

        Parameters
        ----------
        playground_id : str

        name : str

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PlaygroundDetail]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/",
            method="PUT",
            json={
                "name": name,
                "description": description,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundDetail,
                    parse_obj_as(
                        type_=PlaygroundDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_destroy(
        self, playground_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        playground_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_partial_update(
        self,
        playground_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PlaygroundDetail]:
        """
        PATCH handler with superadmin lock and field protection.

        Checks:
        1. Object lock (is_managed=True -> non-superadmins can't modify)
        2. Field protection (non-superadmins can't modify specific fields)

        Parameters
        ----------
        playground_id : str

        name : typing.Optional[str]

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PlaygroundDetail]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/",
            method="PATCH",
            json={
                "name": name,
                "description": description,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundDetail,
                    parse_obj_as(
                        type_=PlaygroundDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_columns_list(
        self, playground_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.List[PlaygroundColumnList]]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        playground_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[PlaygroundColumnList]]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/columns/",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[PlaygroundColumnList],
                    parse_obj_as(
                        type_=typing.List[PlaygroundColumnList],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_columns_create(
        self,
        playground_id: str,
        *,
        playground: str,
        name: str,
        order: typing.Optional[int] = OMIT,
        column_type: typing.Optional[ColumnTypeEnum] = OMIT,
        source_type: typing.Optional[SourceType775Enum] = OMIT,
        linked_prompt_id: typing.Optional[str] = OMIT,
        linked_prompt_version: typing.Optional[int] = OMIT,
        prompt: typing.Optional[typing.Any] = OMIT,
        is_archived: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PlaygroundColumnCreate]:
        """
        Default POST handler with automatic organization injection.

        For CREATE operations:
        - Superadmins can specify organization_id in request body (API key only)
        - Regular users always use their own organization

        Override this method for:
        - POST-for-filtering pattern (delegate to self.get())
        - Custom pre-create validation

        Note: ``inject_target_organization`` is a DEPRECATED ``request.data``-mutating
        shim kept for backward-compat during the DEV-9410 migration. The blessed
        path stamps org via ``get_create_save_kwargs`` → ``perform_create`` → a
        ``read_only`` serializer field. The shim (and these overrides' reliance on
        it) is removed in C18 (DEV-9430) once every view's org field is read_only.

        Parameters
        ----------
        playground_id : str

        playground : str

        name : str

        order : typing.Optional[int]

        column_type : typing.Optional[ColumnTypeEnum]

        source_type : typing.Optional[SourceType775Enum]

        linked_prompt_id : typing.Optional[str]

        linked_prompt_version : typing.Optional[int]

        prompt : typing.Optional[typing.Any]

        is_archived : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PlaygroundColumnCreate]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/columns/",
            method="POST",
            json={
                "playground": playground,
                "name": name,
                "order": order,
                "column_type": column_type,
                "source_type": source_type,
                "linked_prompt_id": linked_prompt_id,
                "linked_prompt_version": linked_prompt_version,
                "prompt": prompt,
                "is_archived": is_archived,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundColumnCreate,
                    parse_obj_as(
                        type_=PlaygroundColumnCreate,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_columns_retrieve(
        self, playground_id: str, column_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PlaygroundColumnDetail]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        playground_id : str

        column_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PlaygroundColumnDetail]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/columns/{jsonable_encoder(column_id)}/",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundColumnDetail,
                    parse_obj_as(
                        type_=PlaygroundColumnDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_columns_update(
        self,
        playground_id: str,
        column_id: str,
        *,
        name: str,
        order: typing.Optional[int] = OMIT,
        column_type: typing.Optional[ColumnTypeEnum] = OMIT,
        source_type: typing.Optional[SourceType775Enum] = OMIT,
        linked_prompt_id: typing.Optional[str] = OMIT,
        linked_prompt_version: typing.Optional[int] = OMIT,
        prompt: typing.Optional[typing.Any] = OMIT,
        is_archived: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PlaygroundColumnDetail]:
        """
        Default PUT handler with automatic organization injection.

        Same behavior as patch() - preserves ownership for superadmins,
        forces user's org for regular users.

        Parameters
        ----------
        playground_id : str

        column_id : str

        name : str

        order : typing.Optional[int]

        column_type : typing.Optional[ColumnTypeEnum]

        source_type : typing.Optional[SourceType775Enum]

        linked_prompt_id : typing.Optional[str]

        linked_prompt_version : typing.Optional[int]

        prompt : typing.Optional[typing.Any]

        is_archived : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PlaygroundColumnDetail]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/columns/{jsonable_encoder(column_id)}/",
            method="PUT",
            json={
                "name": name,
                "order": order,
                "column_type": column_type,
                "source_type": source_type,
                "linked_prompt_id": linked_prompt_id,
                "linked_prompt_version": linked_prompt_version,
                "prompt": prompt,
                "is_archived": is_archived,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundColumnDetail,
                    parse_obj_as(
                        type_=PlaygroundColumnDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_columns_destroy(
        self, playground_id: str, column_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        playground_id : str

        column_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/columns/{jsonable_encoder(column_id)}/",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_columns_partial_update(
        self,
        playground_id: str,
        column_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        order: typing.Optional[int] = OMIT,
        column_type: typing.Optional[ColumnTypeEnum] = OMIT,
        source_type: typing.Optional[SourceType775Enum] = OMIT,
        linked_prompt_id: typing.Optional[str] = OMIT,
        linked_prompt_version: typing.Optional[int] = OMIT,
        prompt: typing.Optional[typing.Any] = OMIT,
        is_archived: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PlaygroundColumnDetail]:
        """
        Default PATCH handler with automatic organization injection.

        For UPDATE operations:
        - Superadmins preserve original ownership (org fields removed from request)
        - Regular users are forced to their own organization

        Override this method only for custom pre-update logic.

        Parameters
        ----------
        playground_id : str

        column_id : str

        name : typing.Optional[str]

        order : typing.Optional[int]

        column_type : typing.Optional[ColumnTypeEnum]

        source_type : typing.Optional[SourceType775Enum]

        linked_prompt_id : typing.Optional[str]

        linked_prompt_version : typing.Optional[int]

        prompt : typing.Optional[typing.Any]

        is_archived : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PlaygroundColumnDetail]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/columns/{jsonable_encoder(column_id)}/",
            method="PATCH",
            json={
                "name": name,
                "order": order,
                "column_type": column_type,
                "source_type": source_type,
                "linked_prompt_id": linked_prompt_id,
                "linked_prompt_version": linked_prompt_version,
                "prompt": prompt,
                "is_archived": is_archived,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundColumnDetail,
                    parse_obj_as(
                        type_=PlaygroundColumnDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_rows_bulk_create(
        self,
        playground_id: str,
        *,
        logs: typing.Sequence[typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DatasetLogsBulkCreateResponse]:
        """
        Default POST handler with automatic organization injection.

        For CREATE operations:
        - Superadmins can specify organization_id in request body (API key only)
        - Regular users always use their own organization

        Override this method for:
        - POST-for-filtering pattern (delegate to self.get())
        - Custom pre-create validation

        Note: ``inject_target_organization`` is a DEPRECATED ``request.data``-mutating
        shim kept for backward-compat during the DEV-9410 migration. The blessed
        path stamps org via ``get_create_save_kwargs`` → ``perform_create`` → a
        ``read_only`` serializer field. The shim (and these overrides' reliance on
        it) is removed in C18 (DEV-9430) once every view's org field is read_only.

        Parameters
        ----------
        playground_id : str

        logs : typing.Sequence[typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DatasetLogsBulkCreateResponse]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/rows/bulk/",
            method="POST",
            json={
                "logs": logs,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DatasetLogsBulkCreateResponse,
                    parse_obj_as(
                        type_=DatasetLogsBulkCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_rows_list_list(
        self,
        playground_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort_by: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PlaygroundRowsListResponse]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        playground_id : str

        page : typing.Optional[int]
            Page number for grouped Playground rows.

        page_size : typing.Optional[int]
            Page size for grouped Playground rows.

        sort_by : typing.Optional[str]
            Sort grouped rows. Defaults to comparison_key. Supports row fields and cell sorting via cells__<experiment_id>.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PlaygroundRowsListResponse]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/rows/list/",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
                "sort_by": sort_by,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundRowsListResponse,
                    parse_obj_as(
                        type_=PlaygroundRowsListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_rows_list_filtered(
        self,
        playground_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort_by: typing.Optional[str] = None,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PlaygroundRowsListResponse]:
        """
        Default POST handler with automatic organization injection.

        For CREATE operations:
        - Superadmins can specify organization_id in request body (API key only)
        - Regular users always use their own organization

        Override this method for:
        - POST-for-filtering pattern (delegate to self.get())
        - Custom pre-create validation

        Note: ``inject_target_organization`` is a DEPRECATED ``request.data``-mutating
        shim kept for backward-compat during the DEV-9410 migration. The blessed
        path stamps org via ``get_create_save_kwargs`` → ``perform_create`` → a
        ``read_only`` serializer field. The shim (and these overrides' reliance on
        it) is removed in C18 (DEV-9430) once every view's org field is read_only.

        Parameters
        ----------
        playground_id : str

        page : typing.Optional[int]
            Page number for grouped Playground rows.

        page_size : typing.Optional[int]
            Page size for grouped Playground rows.

        sort_by : typing.Optional[str]
            Sort grouped rows. Defaults to comparison_key. Supports row fields and cell sorting via cells__<experiment_id>.

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Filter parameters keyed by metric name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PlaygroundRowsListResponse]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/rows/list/",
            method="POST",
            params={
                "page": page,
                "page_size": page_size,
                "sort_by": sort_by,
            },
            json={
                "filters": filters,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundRowsListResponse,
                    parse_obj_as(
                        type_=PlaygroundRowsListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_rows_summary_retrieve(
        self, playground_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PlaygroundRowsSummary]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        playground_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PlaygroundRowsSummary]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/rows/summary/",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundRowsSummary,
                    parse_obj_as(
                        type_=PlaygroundRowsSummary,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_rows_summary_filtered(
        self,
        playground_id: str,
        *,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PlaygroundRowsSummary]:
        """
        Default POST handler with automatic organization injection.

        For CREATE operations:
        - Superadmins can specify organization_id in request body (API key only)
        - Regular users always use their own organization

        Override this method for:
        - POST-for-filtering pattern (delegate to self.get())
        - Custom pre-create validation

        Note: ``inject_target_organization`` is a DEPRECATED ``request.data``-mutating
        shim kept for backward-compat during the DEV-9410 migration. The blessed
        path stamps org via ``get_create_save_kwargs`` → ``perform_create`` → a
        ``read_only`` serializer field. The shim (and these overrides' reliance on
        it) is removed in C18 (DEV-9430) once every view's org field is read_only.

        Parameters
        ----------
        playground_id : str

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Filter parameters keyed by metric name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PlaygroundRowsSummary]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/rows/summary/",
            method="POST",
            json={
                "filters": filters,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundRowsSummary,
                    parse_obj_as(
                        type_=PlaygroundRowsSummary,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_runs_retrieve(
        self, playground_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PlaygroundRun]:
        """
        Declare per-endpoint throttling configuration attributes for views.

        Endpoints can inherit this mixin and set:
        - endpoint_default_rate_limit_per_user_per_min: float | None

        When set (not None), throttling will use ONLY this default RPM for the endpoint
        without requiring API key / org attributes on the request. When unset, the
        standard API key / organization / subscription limits apply.

        Parameters
        ----------
        playground_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PlaygroundRun]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/runs/",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundRun,
                    parse_obj_as(
                        type_=PlaygroundRun,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_playgrounds_runs_create(
        self,
        playground_id: str,
        *,
        column_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        row_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        batch_size: typing.Optional[int] = OMIT,
        concurrency: typing.Optional[int] = OMIT,
        is_tracing_enabled: typing.Optional[bool] = OMIT,
        generation_method: typing.Optional[GenerationMethodEnum] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PlaygroundRun]:
        """
        Default POST handler with automatic organization injection.

        For CREATE operations:
        - Superadmins can specify organization_id in request body (API key only)
        - Regular users always use their own organization

        Override this method for:
        - POST-for-filtering pattern (delegate to self.get())
        - Custom pre-create validation

        Note: ``inject_target_organization`` is a DEPRECATED ``request.data``-mutating
        shim kept for backward-compat during the DEV-9410 migration. The blessed
        path stamps org via ``get_create_save_kwargs`` → ``perform_create`` → a
        ``read_only`` serializer field. The shim (and these overrides' reliance on
        it) is removed in C18 (DEV-9430) once every view's org field is read_only.

        Parameters
        ----------
        playground_id : str

        column_ids : typing.Optional[typing.Sequence[str]]

        row_ids : typing.Optional[typing.Sequence[str]]

        batch_size : typing.Optional[int]

        concurrency : typing.Optional[int]

        is_tracing_enabled : typing.Optional[bool]

        generation_method : typing.Optional[GenerationMethodEnum]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PlaygroundRun]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/playgrounds/{jsonable_encoder(playground_id)}/runs/",
            method="POST",
            json={
                "column_ids": column_ids,
                "row_ids": row_ids,
                "batch_size": batch_size,
                "concurrency": concurrency,
                "is_tracing_enabled": is_tracing_enabled,
                "generation_method": generation_method,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlaygroundRun,
                    parse_obj_as(
                        type_=PlaygroundRun,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
