# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.span1behavior import Span1Behavior
from ..types.span1score_response import Span1ScoreResponse
from ..types.span1span import Span1Span
from .raw_client import AsyncRawRespanModelsClient, RawRespanModelsClient
from .types.span1score_request_respan_params import Span1ScoreRequestRespanParams

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RespanModelsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRespanModelsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRespanModelsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRespanModelsClient
        """
        return self._raw_client

    def score_span_behaviors(
        self,
        *,
        span: Span1Span,
        behaviors: typing.Sequence[Span1Behavior],
        model: typing.Optional[str] = OMIT,
        respan_params: typing.Optional[Span1ScoreRequestRespanParams] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Span1ScoreResponse:
        """
        Run inference with Span-01, Respan's first-party classification model for agent traces. Provide an interaction in `span` and plain-language definitions in `behaviors`. Your application can use the model's predictions for evaluations, guardrails, routing, and monitoring.

        For each definition, the model returns the probabilities that it is present, absent, or not observable; the three probabilities sum to approximately 1. The example classifies a support interaction for user frustration and an assistant apology. Replace those definitions to apply the model to your own use case.

        Parameters
        ----------
        span : Span1Span
            The interaction to classify: preceding messages in input and the target turn in output.

        behaviors : typing.Sequence[Span1Behavior]
            The rubric: one ID and plain-language definition per behavior. There is no per-request behavior-count cap. Definitions count toward usage.input_tokens.

        model : typing.Optional[str]
            Use span-01-free or span-01-pro. Omit for span-01-free.

        respan_params : typing.Optional[Span1ScoreRequestRespanParams]
            Optional Respan gateway parameters for logging and attribution. These are removed before the request reaches the scorer. See the Respan gateway parameters guide for other supported fields.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Span1ScoreResponse
            Behavior probabilities for the submitted span. The example is the captured response to the request shown.

        Examples
        --------
        from respan import RespanClient, Span1Behavior, Span1Message, Span1Span
        from respan.respan_models import Span1ScoreRequestRespanParams

        client = RespanClient(
            authorization="YOUR_AUTHORIZATION",
            respan_api_key="YOUR_RESPAN_API_KEY",
        )
        client.respan_models.score_span_behaviors(
            model="span-01-free",
            span=Span1Span(
                input=[
                    Span1Message(
                        role="user",
                        content="This is the third time my order is late.",
                    )
                ],
                output=Span1Message(
                    role="assistant",
                    content="I am sorry, let me check on that for you.",
                ),
            ),
            behaviors=[
                Span1Behavior(
                    id="frustrated",
                    definition="The user expresses frustration or anger.",
                ),
                Span1Behavior(
                    id="apology",
                    definition="The assistant apologizes for a problem.",
                ),
            ],
            respan_params=Span1ScoreRequestRespanParams(
                customer_identifier="acme-1042",
            ),
        )
        """
        _response = self._raw_client.score_span_behaviors(
            span=span, behaviors=behaviors, model=model, respan_params=respan_params, request_options=request_options
        )
        return _response.data


class AsyncRespanModelsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRespanModelsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRespanModelsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRespanModelsClient
        """
        return self._raw_client

    async def score_span_behaviors(
        self,
        *,
        span: Span1Span,
        behaviors: typing.Sequence[Span1Behavior],
        model: typing.Optional[str] = OMIT,
        respan_params: typing.Optional[Span1ScoreRequestRespanParams] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Span1ScoreResponse:
        """
        Run inference with Span-01, Respan's first-party classification model for agent traces. Provide an interaction in `span` and plain-language definitions in `behaviors`. Your application can use the model's predictions for evaluations, guardrails, routing, and monitoring.

        For each definition, the model returns the probabilities that it is present, absent, or not observable; the three probabilities sum to approximately 1. The example classifies a support interaction for user frustration and an assistant apology. Replace those definitions to apply the model to your own use case.

        Parameters
        ----------
        span : Span1Span
            The interaction to classify: preceding messages in input and the target turn in output.

        behaviors : typing.Sequence[Span1Behavior]
            The rubric: one ID and plain-language definition per behavior. There is no per-request behavior-count cap. Definitions count toward usage.input_tokens.

        model : typing.Optional[str]
            Use span-01-free or span-01-pro. Omit for span-01-free.

        respan_params : typing.Optional[Span1ScoreRequestRespanParams]
            Optional Respan gateway parameters for logging and attribution. These are removed before the request reaches the scorer. See the Respan gateway parameters guide for other supported fields.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Span1ScoreResponse
            Behavior probabilities for the submitted span. The example is the captured response to the request shown.

        Examples
        --------
        import asyncio

        from respan import AsyncRespanClient, Span1Behavior, Span1Message, Span1Span
        from respan.respan_models import Span1ScoreRequestRespanParams

        client = AsyncRespanClient(
            authorization="YOUR_AUTHORIZATION",
            respan_api_key="YOUR_RESPAN_API_KEY",
        )


        async def main() -> None:
            await client.respan_models.score_span_behaviors(
                model="span-01-free",
                span=Span1Span(
                    input=[
                        Span1Message(
                            role="user",
                            content="This is the third time my order is late.",
                        )
                    ],
                    output=Span1Message(
                        role="assistant",
                        content="I am sorry, let me check on that for you.",
                    ),
                ),
                behaviors=[
                    Span1Behavior(
                        id="frustrated",
                        definition="The user expresses frustration or anger.",
                    ),
                    Span1Behavior(
                        id="apology",
                        definition="The assistant apologizes for a problem.",
                    ),
                ],
                respan_params=Span1ScoreRequestRespanParams(
                    customer_identifier="acme-1042",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.score_span_behaviors(
            span=span, behaviors=behaviors, model=model, respan_params=respan_params, request_options=request_options
        )
        return _response.data
